[GLOBAL_PRAGMA]
grflangid = "0x1b"
plural = "0"
gender = "male"

[STR_GRF_DESCRIPTION]
base = "Lisensie: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Trein dravermoÃ«"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "Klein"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "Wonderlik"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "Uitbundig"

[STR_BADGE_POWER_SOURCE_DIESEL]
base = "(Diesel)"

[STR_BADGE_POWER_SOURCE_STEAM]
base = "(Stoom)"

[STR_WAGON_NAME_CABOOSE_CAR]
base = "Kondukteurs Wa"

[STR_WAGON_NAME_FLAT_CAR]
base = "Plat Wa"

[STR_WAGON_NAME_LIVESTOCK_CAR]
base = "Lewendehawe Wa"

[STR_WAGON_NAME_MAIL_CAR]
base = "Pos Wa"

[STR_WAGON_NAME_OPEN_CAR]
base = "Oop Wa"

[STR_WAGON_NAME_PASSENGER_CAR]
base = "Passasiersmotor"

