[GLOBAL_PRAGMA]
grflangid = "0x22"
plural = "0"
gender = "Masculin Femenin"

[STR_GRF_DESCRIPTION]
base = "Llicència: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Capacitat del tren"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_DESC]
base = "Ajusta la capacitat del tren per a estils de joc alternatius.{}{}Puny: {GOLD}Reducció del 33%{BLACK}{}Fantàstica: {GOLD}per defecte{BLACK}{}Excessiva: {GOLD}Increment del 33%{BLACK}{}Desmesurada: {GOLD}Increment del 77%{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "Diminuta"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "Fantàstica"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "Excessiva"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_3]
base = "Desmesurada"

[STR_PARAM_WAGON_COLOUR_RANDOMISATION]
base = "Selecció de color de cotxe aleatori"

[STR_BADGE_POWER_SOURCE_DIESEL]
base = "Diesel"

[STR_BADGE_POWER_SOURCE_METRO]
base = "Metro"

[STR_BADGE_POWER_SOURCE_STEAM]
base = "Vapor"

[STR_WAGON_NAME_ALIGNMENT_CAR]
base = "Cotxe d'alineament"

[STR_WAGON_NAME_COIL_BUGGY_CAR]
base = "Cotxe de bobinat"

[STR_WAGON_NAME_BOLSTER_CAR]
base = "Cotxe de càrrega plana"

[STR_WAGON_NAME_CABOOSE_CAR]
base = "Furgó de Cua"

[STR_WAGON_NAME_CARBON_BLACK_HOPPER_CAR]
base = "Vagó carboner"

[STR_WAGON_NAME_CRYO_TANK_CAR]
base = "Tanc d'hidrògen líquid"

[STR_WAGON_NAME_CURTAIN_SIDE_BOX_CAR]
base = "Vagó de cortina lateral"

[STR_WAGON_NAME_EXPRESS_CAR]
base = "Vagó express"

[STR_WAGON_NAME_EXPRESS_INTERMODAL_CAR]
base = "Vagó contenidor express"

[STR_WAGON_NAME_FLAT_CAR]
base = "Vagó pla"

[STR_WAGON_NAME_HOPPER_CAR]
base = "Vagó tolva"

[STR_WAGON_NAME_HST_PASSENGER_CAR]
base = "Vagó de passatge d'alta velocitat"

[STR_WAGON_NAME_INGOT_CAR]
base = "Vagó metall"

[STR_WAGON_NAME_INTERMODAL_CAR]
base = "Vagó contenidor"

[STR_WAGON_NAME_LIVESTOCK_CAR]
base = "Vagó ramader"

[STR_WAGON_NAME_LOG_CAR]
base = "Cotxe transportador de fusta"

[STR_WAGON_NAME_MAIL_CAR]
base = "Cotxe de correu"

[STR_WAGON_NAME_OPEN_CAR]
base = "Cotxe obert"

[STR_WAGON_NAME_PASSENGER_CAR]
base = "Cotxe de passatge"

[STR_WAGON_NAME_RESTAURANT_CAR]
base = "Cotxe restaurant"

[STR_WAGON_NAME_ROCK_HOPPER_CAR]
base = "Cotxe de minerals"

[STR_WAGON_NAME_SLAG_LADLE_CAR]
base = "Cotxe de deixalla metalúrgica"

[STR_WAGON_NAME_SLIDING_ROOF_CAR]
base = "Cotxe de sostre deslliçant"

[STR_WAGON_NAME_TORPEDO_CAR]
base = "Cotxe torpedo"

[STR_BADGE_ROLE]
base = "Rol"

[STR_BADGE_ROLE_DRIVING_CAB]
base = "Cabina de Conducció"

[STR_BADGE_ROLE_GENERAL_PURPOSE]
base = "Propòsit General"

[STR_BADGE_ROLE_GENERAL_PURPOSE_EXPRESS]
base = "Propòsit General / Express"

[STR_BADGE_ROLE_INTERCITY_EXPRESS]
base = "Alta Velocitat"

[STR_BADGE_ROLE_LOLZ]
base = "Gronk!"

[STR_BADGE_ROLE_METRO]
base = "Urbà d'Alta Capacitat"

[STR_WAGONS_ADD_POWER_CAB]
base = "Potència (Distribuida): {GOLD}{POWER} per cada {STRING} unitat adjuntada"

[STR_WAGONS_ADD_POWER_MIDDLE]
base = "Potència (Distribuida): {GOLD}{POWER} al adjuntar {STRING} unitat"

[STR_SPRITES_COMPLETE]
base = "{}Sprites Completats: {GOLD}Oh i tant"

[STR_SPRITES_INCOMPLETE]
base = "{}Sprites Completats: {GOLD}No pas"
