[GLOBAL_PRAGMA]
grflangid = "0x38"
plural = "6"
gender = "male female middle"
case = "aku dat gen ins lok nom vok"

[STR_GRF_DESCRIPTION]
base = "Licenca: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Kapacitet vlaka"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "Slabašan"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "Divan"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "Prekomjeran"

[STR_BADGE_POWER_SOURCE_DIESEL]
base = "Dizel"

[STR_BADGE_POWER_SOURCE_ELECTRODIESEL]
base = "Elektro-dizel"

[STR_BADGE_POWER_SOURCE_METRO]
base = "Metro"

[STR_BADGE_POWER_SOURCE_STEAM]
base = "Para"

[STR_WAGON_NAME_ALIGNMENT_CAR]
base = "Vagon za poravnanje"

[STR_WAGON_NAME_CABOOSE_CAR]
base = "Vagon za kočničara"

[STR_WAGON_NAME_CRYO_TANK_CAR]
base = "Krio-cisterna"

[STR_WAGON_NAME_CURTAIN_SIDE_BOX_CAR]
base = "Vagon sa stranicama od cerade"

[STR_WAGON_NAME_EXPRESS_CAR]
base = "Ekspresni vagon"

[STR_WAGON_NAME_FLAT_CAR]
base = "Plato-vagon"

[STR_WAGON_NAME_HST_PASSENGER_CAR]
base = "Putnički vagon za vlak velike brzine"

[STR_WAGON_NAME_INTERMODAL_CAR]
base = "Intermodalni vagon"

[STR_WAGON_NAME_LIVESTOCK_CAR]
base = "Vagon za stoku"

[STR_WAGON_NAME_MAIL_CAR]
base = "Poštanski vagon"

[STR_WAGON_NAME_OPEN_CAR]
base = "Otvoreni vagon"

[STR_WAGON_NAME_PASSENGER_CAR]
base = "Putnički vagon"

[STR_WAGON_NAME_DROP_SIDE_FLAT_CAR]
base = "Plato-vagon"

[STR_WAGON_NAME_TORPEDO_CAR]
base = "Vagon-torpedo"

[STR_BADGE_ROLE]
base = "Uloga"

[STR_BADGE_ROLE_GENERAL_PURPOSE]
base = "Opća namjena"

[STR_BADGE_ROLE_GENERAL_PURPOSE_EXPRESS]
base = "Opća namjena / ekspresni"

[STR_BADGE_ROLE_INTERCITY_EXPRESS]
base = "Visoka brzina"

[STR_BADGE_ROLE_METRO]
base = "Gradski visokog kapaciteta"

[STR_SPRITES_COMPLETE]
base = "{}Kompletirani spriteovi: {GOLD}Da"

[STR_SPRITES_INCOMPLETE]
base = "{}Kompletirani spriteovi: {GOLD}Ne"
