[GLOBAL_PRAGMA]
grflangid = "0x15"
plural = "10"
gender = "fp map f mnp m n np"
case = "acc nom loc big voc ins dat small gen"

[STR_GRF_DESCRIPTION]
base = "Licence: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Kapacita vlaku"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "Maličká"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "Obrovská"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "Nadměrná"

[STR_BADGE_POWER_SOURCE_DIESEL]
base = "Dieselová"

[STR_BADGE_POWER_SOURCE_ELECTRODIESEL]
base = "Hybridní"

[STR_BADGE_POWER_SOURCE_METRO]
base = "Metro vůz"

[STR_BADGE_POWER_SOURCE_STEAM]
base = "Parní"

[STR_BADGE_WAGON_LENGTH_SMALL]
base = "Malý"

[STR_BADGE_WAGON_LENGTH_MEDIUM]
base = "Střední"

[STR_BADGE_WAGON_LENGTH_LARGE]
base = "Velký"

[STR_WAGON_NAME_ALIGNMENT_CAR]
base = "Zarovnávací vůz"

[STR_WAGON_NAME_CABOOSE_CAR]
base = "Služební vůz"

[STR_WAGON_NAME_CRYO_TANK_CAR]
base = "Chladící cisterna"

[STR_WAGON_NAME_CURTAIN_SIDE_BOX_CAR]
base = "Kontejnerový vůz"

[STR_WAGON_NAME_EXPRESS_CAR]
base = "Expresní vůz"

[STR_WAGON_NAME_EXPRESS_INTERMODAL_CAR]
base = "Expresní kontejnerový vůz"

[STR_WAGON_NAME_FLAT_CAR]
base = "Nízkostěnný vůz"

[STR_WAGON_NAME_HST_PASSENGER_CAR]
base = "HST osobní vůz"

[STR_WAGON_NAME_INTERMODAL_CAR]
base = "Kontejnerový vůz"

[STR_WAGON_NAME_LIVESTOCK_CAR]
base = "Vůz na dobytek"

[STR_WAGON_NAME_MAIL_CAR]
base = "Poštovní vůz"

[STR_WAGON_NAME_OPEN_CAR]
base = "Otevřený vůz"

[STR_WAGON_NAME_PASSENGER_CAR]
base = "Vůz pro cestující"

[STR_WAGON_NAME_DROP_SIDE_FLAT_CAR]
base = "Plošinový vůz"

[STR_WAGON_NAME_TORPEDO_CAR]
base = "Torpédový vůz"

[STR_BADGE_ROLE]
base = "{BLACK}Role: {GOLD}{STRING}"

[STR_BADGE_ROLE_GENERAL_PURPOSE]
base = "Obecný účel"

[STR_BADGE_ROLE_GENERAL_PURPOSE_EXPRESS]
base = "Obecný účel /Expres"

[STR_BADGE_ROLE_INTERCITY_EXPRESS]
base = "Vysoká rychlost"

[STR_BADGE_ROLE_METRO]
base = "Vysoká městská kapacita"

[STR_BADGE_ROLE_LOLZ]
base = "Lolz"

[STR_WAGONS_ADD_POWER_CAB]
base = "Výkon (Distribuováno): {GOLD}{POWER} za {STRING} připojený vagon"

[STR_WAGONS_ADD_POWER_MIDDLE]
base = "Výkon (Distribuováno): {GOLD} {POWER}, když je připojen k  {STRING} jednotce"

[STR_SPRITES_COMPLETE]
base = "Grafika dokončena:  {GOLD} Jo"

[STR_SPRITES_INCOMPLETE]
base = "Grafika dokončena: {GOLD} Ne, ani náhodou"
