[GLOBAL_PRAGMA]
grflangid = "0x1f"
plural = "0"

[STR_GRF_DESCRIPTION]
base = "Licentie: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Treincapaciteit"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "Zielig"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "Geweldig"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "Extravagant"

[STR_BADGE_POWER_SOURCE_DIESEL]
base = "Diesel"

[STR_BADGE_POWER_SOURCE_METRO]
base = "Metro"

[STR_BADGE_POWER_SOURCE_STEAM]
base = "Stoom"

[STR_WAGON_NAME_ALIGNMENT_CAR]
base = "Lijnwagen"

[STR_WAGON_NAME_CABOOSE_CAR]
base = "Remwagon"

[STR_WAGON_NAME_CRYO_TANK_CAR]
base = "Cryotanker"

[STR_WAGON_NAME_CURTAIN_SIDE_BOX_CAR]
base = "Voertuig met schuifdeuren"

[STR_WAGON_NAME_EXPRESS_CAR]
base = "Expreswagen"

[STR_WAGON_NAME_EXPRESS_INTERMODAL_CAR]
base = "Expresse-containerwagon"

[STR_WAGON_NAME_FLAT_CAR]
base = "Platte wagon"

[STR_WAGON_NAME_HST_PASSENGER_CAR]
base = "HST-passagiersrijtuig"

[STR_WAGON_NAME_INTERMODAL_CAR]
base = "Containerwagon"

[STR_WAGON_NAME_LIVESTOCK_CAR]
base = "Veewagon"

[STR_WAGON_NAME_MAIL_CAR]
base = "Postwagon"

[STR_WAGON_NAME_OPEN_CAR]
base = "Open wagon"

[STR_WAGON_NAME_PASSENGER_CAR]
base = "Passagiersrijtuig"

[STR_WAGON_NAME_TORPEDO_CAR]
base = "Torpedowagen"

[STR_BADGE_ROLE]
base = "Rol"

[STR_BADGE_ROLE_GENERAL_PURPOSE]
base = "Algemeen gebruik"

[STR_BADGE_ROLE_GENERAL_PURPOSE_EXPRESS]
base = "Algemeen gebruik / expresse"

[STR_BADGE_ROLE_INTERCITY_EXPRESS]
base = "Hoge snelheid"

[STR_BADGE_ROLE_METRO]
base = "Hoge capaciteit stedelijk"

[STR_BADGE_ROLE_LOLZ]
base = "Lolz"

[STR_WAGONS_ADD_POWER_CAB]
base = "Vermogen (verdeeld): {GOLD}{POWER} per aangesloten {STRING} eenheid"

[STR_WAGONS_ADD_POWER_MIDDLE]
base = "Vermogen (verdeeld): {GOLD}{POWER} bij aansluiten op {STRING} eenheid"

[STR_SPRITES_COMPLETE]
base = "{}Sprites gereed: {GOLD}Ja"

[STR_SPRITES_INCOMPLETE]
base = "{}Sprites gereed: {GOLD}Nee"
