[GLOBAL_PRAGMA]
grflangid = "0x1f"
plural = "0"

[STR_GRF_DESCRIPTION]
base = "Licentie: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Treincapaciteit"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "Zielig"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "Geweldig"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "Extravagant"

[STR_NAME_SUFFIX_DIESEL]
base = "Diesel"

[STR_NAME_SUFFIX_ELECTRODIESEL]
base = "Diesel-elektrisch"

[STR_NAME_SUFFIX_METRO]
base = "Metro"

[STR_NAME_SUFFIX_STEAM]
base = "Stoom"

[STR_NAME_SUFFIX_SMALL]
base = "Klein"

[STR_NAME_SUFFIX_MEDIUM]
base = "Gemiddeld"

[STR_NAME_SUFFIX_LARGE]
base = "Groot"

[STR_NAME_SUFFIX_ALIGNMENT_CAR]
base = "Lijnwagen"

[STR_NAME_SUFFIX_BOX_CAR]
base = "Gesloten wagon"

[STR_NAME_SUFFIX_CABOOSE_CAR]
base = "Remwagon"

[STR_NAME_SUFFIX_CRYO_TANK_CAR]
base = "Cryotanker"

[STR_NAME_SUFFIX_CURTAIN_SIDE_BOX_CAR]
base = "Voertuig met schuifdeuren"

[STR_NAME_SUFFIX_DUMP_CAR]
base = "Mineralenwagon"

[STR_NAME_SUFFIX_DUMP_CAR_HIGH_SIDE]
base = "Mineralenwagon met hoge zijkant"

[STR_NAME_SUFFIX_FOOD_TANK_CAR]
base = "Voedseltanker"

[STR_NAME_SUFFIX_EXPRESS_CAR]
base = "Expreswagen"

[STR_NAME_SUFFIX_EXPRESS_INTERMODAL_CAR]
base = "Expresse-containerwagon"

[STR_NAME_SUFFIX_FLAT_CAR]
base = "Platte wagon"

[STR_NAME_SUFFIX_HST_PASSENGER_CAR]
base = "HST-passagiersrijtuig"

[STR_NAME_SUFFIX_INTERMODAL_CAR]
base = "Containerwagon"

[STR_NAME_SUFFIX_LIVESTOCK_CAR]
base = "Veewagon"

[STR_NAME_SUFFIX_MAIL_CAR]
base = "Postwagon"

[STR_NAME_SUFFIX_OPEN_CAR]
base = "Open wagon"

[STR_NAME_SUFFIX_PASSENGER_CAR]
base = "Passagiersrijtuig"

[STR_NAME_SUFFIX_DROPSIDE_FLAT_CAR]
base = "Plaatwagon"

[STR_NAME_SUFFIX_REEFER_CAR_TYPE_1]
base = "Koelwagon"

[STR_NAME_SUFFIX_SILO_CAR]
base = "Silowagon"

[STR_NAME_SUFFIX_SLIDING_WALL_CAR]
base = "Voertuig met schuifdeuren"

[STR_NAME_SUFFIX_TANK_CAR]
base = "Tanker"

[STR_NAME_SUFFIX_TARPAULIN_CAR]
base = "Wagon met dekzeil"

[STR_NAME_SUFFIX_TORPEDO_CAR]
base = "Torpedowagen"

[STR_ROLE]
base = "{BLACK}Rol: {GOLD}{STRING}"

[STR_ROLE_FREIGHT]
base = "Vracht"

[STR_ROLE_GENERAL_PURPOSE]
base = "Algemeen gebruik"

[STR_ROLE_GENERAL_PURPOSE_EXPRESS]
base = "Algemeen gebruik / expresse"

[STR_ROLE_INTERCITY_EXPRESS]
base = "Hoge snelheid"

[STR_ROLE_METRO]
base = "Hoge capaciteit stedelijk"

[STR_ROLE_VERY_HIGH_SPEED]
base = "Zeer hoge snelheid"

[STR_ROLE_LOLZ]
base = "Lolz"

[STR_WAGONS_ADD_POWER_CAB]
base = "Vermogen (verdeeld): {GOLD}{POWER} per aangesloten {STRING} eenheid"

[STR_WAGONS_ADD_POWER_MIDDLE]
base = "Vermogen (verdeeld): {GOLD}{POWER} bij aansluiten op {STRING} eenheid"

[STR_SPRITES_COMPLETE]
base = "{}Sprites gereed: {GOLD}Ja"

[STR_SPRITES_INCOMPLETE]
base = "{}Sprites gereed: {GOLD}Nee"
