[GLOBAL_PRAGMA]
# this is the default translation and is en-gb
grflangid = 0x01
plural = 0

[STR_GRF_DESCRIPTION]
base = "License: {SILVER}GPL v2{}{BLACK}"


# parameters (action 14 etc)

[STR_PARAM_VEHICLE_AVAILABILITY_ENGINES]
base = "Engines"

[STR_PARAM_VEHICLE_AVAILABILITY_ENGINES_DESC]
base = "Play with all engines, a simplified set of engines, or no engines at all. {}{}{SILVER}All: {BLACK}the full range of Iron Horse engines will be available. {}{}{SILVER}Simplified: {BLACK}there will be fewer Iron Horse engines available, and eye-candy trains like snowploughs, driving cab cars and very slow locomotives will not be available.{}{}{SILVER}None: {BLACK}no Iron Horse engines will be available. Use this to get a wagons-only version of Iron Horse (requires that engines are provided by another grf, otherwise wagons will not be available)."

[STR_PARAM_VEHICLE_AVAILABILITY_WAGONS]
base = "Wagons"

[STR_PARAM_VEHICLE_AVAILABILITY_WAGONS_DESC]
base = "Play with all wagons, a simplified set of wagons, or no wagons at all. {}{}{SILVER}All: {BLACK}the full range of Iron Horse wagons will be available. {}{}{SILVER}Simplified: {BLACK}there will be fewer Iron Horse wagons available. {}{}{SILVER}None: {BLACK}no Iron Horse wagons will be available."

[STR_PARAM_VEHICLE_AVAILABILITY_OPTION_0]
base = "All"

[STR_PARAM_VEHICLE_AVAILABILITY_OPTION_1]
base = "Simplified"

[STR_PARAM_VEHICLE_AVAILABILITY_OPTION_2]
base = "None"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Train capacity"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_DESC]
base = "Adjust vehicle capacity for alternative gameplay styles.{}{}{SILVER}Nanoscopic: {BLACK}77% reduction{SILVER}{}Puny: {BLACK}33% reduction{SILVER}{}Marvellous: {BLACK}default{SILVER}{}Excessive: {BLACK}33% increase{SILVER}{}Outrageous: {BLACK}77% increase{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "Nanoscopic"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "Puny"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "Marvellous (default)"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_3]
base = "Excessive"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_4]
base = "Outrageous"

[STR_PARAM_WAGON_COLOUR_RANDOMISATION]
base = "Wagon colour fading"

[STR_PARAM_WAGON_COLOUR_RANDOMISATION_STRATEGY_DESC]
base = "Faded freight wagon colours add variety to trains (random chance each wagon is faded)."

[STR_PARAM_VEHICLE_RANDOM_REVERSE_ON_BUILD]
base = "Build some vehicles reversed"

[STR_PARAM_VEHICLE_RANDOM_REVERSE_ON_BUILD_DESC]
base = "Iron Horse will randomly build some vehicles as reversed, for example steam tank engines or diesel engines that have cabs at both ends.  This feature can be turned off with this parameter setting."

[STR_ERROR_INFLATION_INCOMPATIBLE]
base = "Iron Horse is not compatible with OpenTTD Inflation. Please turn Inflation off in OpenTTD settings."
# substrings of the grf name _could_ be used here
ibex = "Iron Ibex is not compatible with OpenTTD Inflation. Please turn Inflation off in OpenTTD settings."
moose = "Iron Moose is not compatible with OpenTTD Inflation. Please turn Inflation off in OpenTTD settings."

[STR_ERROR_TERMITE_DEPRECATED]
base = "Iron Horse now includes the railtypes from Termite. Please remove Termite from the NewGRF list and try a new game. Thanks."
# substrings of the grf name _could_ be used here
ibex = "Iron Ibex includes the railtypes from Termite. Please remove Termite from the NewGRF list and try a new game. Thanks."
moose = "Iron Moose includes the railtypes from Termite. Please remove Termite from the NewGRF list and try a new game. Thanks."

# livery badges

[STR_BADGE_LIVERY]
base = "Livery"

# freight wagon liveries

[STR_BADGE_LIVERY_COMPANY_COLOUR]
base = "Company Colour"

[STR_BADGE_LIVERY_COMPLEMENT_COMPANY_COLOUR]
base = "Company Colour Adjacent"

[STR_BADGE_LIVERY_RANDOM_LIVERIES_COMPLEMENT_COMPANY_COLOUR]
base = "Company Colour Mix"

[STR_BADGE_LIVERY_RANDOM_LIVERIES_VARIETY_GEMSTONE]
base = "Gemstone"

[STR_BADGE_LIVERY_RANDOM_LIVERIES_VARIETY_LIMEWASH]
base = "Limewash"

[STR_BADGE_LIVERY_RANDOM_LIVERIES_BUMBLEBEE]
base = "Bumblebee"

[STR_BADGE_LIVERY_RANDOM_LIVERIES_GREY_RUST_NIGHTSHADE]
base = "Workday"

[STR_BADGE_LIVERY_RANDOM_LIVERIES_VIOLET_TEAL_OCEAN_TEAL]
base = "Soap Bubbles"

[STR_BADGE_LIVERY_RANDOM_LIVERIES_SILVER_PEWTER]
base = "Platinum"

[STR_BADGE_LIVERY_RANDOM_LIVERIES_CLOVER_OCHRE_SILVER_SULPHUR]
base = "Clover Fields"

[STR_BADGE_LIVERY_RANDOM_LIVERIES_CLOVER_OCHRE_SULPHUR]
base = "Pineapple"

[STR_BADGE_LIVERY_RANDOM_LIVERIES_SULPHUR_OCHRE]
base = "Sulphur Mix"

[STR_BADGE_LIVERY_RANDOM_LIVERIES_OIL_BLACK_OBSIDIAN]
base = "Obsidian"

[STR_BADGE_LIVERY_RANDOM_LIVERIES_OIL_BLACK_OBSIDIAN_NIGHTSHADE]
base = "Night Black"

[STR_BADGE_LIVERY_RANDOM_LIVERIES_OCHRE_SAND]
base = "Desert Sand"

[STR_BADGE_LIVERY_RANDOM_LIVERIES_TEAL_PEWTER_SILVER]
base = "Ocean Silver"

[STR_BADGE_LIVERY_RANDOM_LIVERIES_TEAL_OCEAN_TEAL]
base = "Ocean Teal"

[STR_BADGE_LIVERY_RANDOM_LIVERIES_SILVER_GREY_PEWTER]
base = "Silver Smoke"

[STR_BADGE_LIVERY_RANDOM_LIVERIES_OXIDE_RUST]
base = "Rustbelt"

[STR_BADGE_LIVERY_FREIGHT_BONUS_OBSIDIAN]
base = "Obsidian"

[STR_BADGE_LIVERY_FREIGHT_BONUS_OXIDE_RUST]
base = "Rustbelt"

[STR_BADGE_LIVERY_FREIGHT_BONUS_TEAL]
base = "Ocean Teal"

[STR_BADGE_LIVERY_FREIGHT_GREY]
base = "Grey"

[STR_BADGE_LIVERY_FREIGHT_MIST]
base = "Mist"

[STR_BADGE_LIVERY_FREIGHT_PEWTER]
base = "Pewter"

[STR_BADGE_LIVERY_FREIGHT_RED]
base = "Flame Red"

# other liveries
# _might_ need to use roster-specific strings, but we'll see

[STR_BADGE_LIVERY_SPECIAL_CIRCUMSTANCES]
base = "Special Circumstances"

[STR_BADGE_LIVERY_BANGER_BLUE]
base = "Basic Banger"

[STR_BADGE_LIVERY_CLASSIC_LINES]
base = "Classic Lines"

[STR_BADGE_LIVERY_DUTCH]
base = "Double Dutch"

[STR_BADGE_LIVERY_FARMFLOW]
base = "Farmflow"

[STR_BADGE_LIVERY_FREIGHT_BLACK]
base = "Dark Horse"

[STR_BADGE_LIVERY_FREIGHTLINER_GBRF]
base = "BoxFreight"

[STR_BADGE_LIVERY_INDUSTRIAL_YELLOW]
base = "Works Unit"

[STR_BADGE_LIVERY_INTERCITY_RASPBERRY_RIPPLE]
base = "Fruit Ripple"

[STR_BADGE_LIVERY_METROLAND]
base = "Metroland"

[STR_BADGE_LIVERY_RAILFREIGHT_RED_STRIPE]
base = "Railslate Grey"

[STR_BADGE_LIVERY_RAILFREIGHT_TRIPLE_GREY]
base = "Sector Connector"

[STR_BADGE_LIVERY_ROYAL_MAIL_RES]
base = "Mail by Rail"

[STR_BADGE_LIVERY_SHOW_PONY]
base = "Show Pony"

[STR_BADGE_LIVERY_SLABSIDE]
base = "Conventional Wisdom"

[STR_BADGE_LIVERY_STOCK_STANDARD]
base = "Stock Standard"

[STR_BADGE_LIVERY_SWOOSH]
base = "SWOOSH"

[STR_BADGE_LIVERY_SWOOSH_2000]
base = "SWOOSH_2000"

[STR_BADGE_LIVERY_SUPERGRAPHIC]
base = "Supergraphic"

[STR_BADGE_LIVERY_VANILLA]
base = "VANILLA"

[STR_BADGE_LIVERY_WHITE_STRIPE]
base = "WHITE_STRIPE"

[STR_BADGE_LIVERY_WORKHORSE]
base = "Work Horse"

# behaviour badges (behaviour and role are different)

[STR_BADGE_BEHAVIOUR]
base = "Behaviour"

[STR_BADGE_BEHAVIOUR_CABOOSE]
base = "No gameplay effect"

[STR_BADGE_BEHAVIOUR_EASTER_EGG_HAULAGE_SPEED_BONUS]
base = "Express haulable"

[STR_BADGE_BEHAVIOUR_RANDOMISED_WAGON]
base = "Randomised choice of wagon"

[STR_BADGE_BEHAVIOUR_RESTAURANT_CAR]
base = "Eliminates running costs for all Passenger Coaches and High Speed Coaches in the train"

# role badges

[STR_BADGE_ROLE]
base = "Role"

[STR_BADGE_ROLE_DRIVING_CAB]
base = "Driving Cab{BLACK} - attach to front or rear of train, with at least one other engine"

[STR_BADGE_ROLE_GENERAL_PURPOSE]
base = "General Purpose"

[STR_BADGE_ROLE_GENERAL_PURPOSE_EXPRESS]
base = "General Purpose / Express"

[STR_BADGE_ROLE_GENERAL_PURPOSE_FREIGHT]
base = "General Purpose / Freight"

[STR_BADGE_ROLE_GRONK]
base = "Gronk!"

[STR_BADGE_ROLE_INTERCITY_EXPRESS]
base = "InterCity Express"

[STR_BADGE_ROLE_LOLZ]
base = "Lolz"

[STR_BADGE_ROLE_METRO]
base = "Very High Capacity Urban"

[STR_BADGE_ROLE_SUBURBAN]
base = "General Purpose / High Capacity"

# gen badges

[STR_BADGE_GEN]
base = "Gen"

[STR_BADGE_GEN_1]
base = "1"

[STR_BADGE_GEN_2]
base = "2"

[STR_BADGE_GEN_3]
base = "3"

[STR_BADGE_GEN_4]
base = "4"

[STR_BADGE_GEN_5]
base = "5"

[STR_BADGE_GEN_6]
base = "6"

# special features badges

[STR_BADGE_SPECIAL_FLAGS]
base = "Special Features"

[STR_BADGE_SPECIAL_FLAG_TILT]
base = "Tilts for faster cornering"

# power source badges

[STR_BADGE_POWER_SOURCE_BATTERY_HYBRID]
base = "Battery Hybrid"

[STR_BADGE_POWER_SOURCE_DIESEL]
base = "Diesel"

[STR_BADGE_POWER_SOURCE_OHLE]
base = "Electric"

[STR_BADGE_POWER_SOURCE_METRO]
base = "Metro"

[STR_BADGE_POWER_SOURCE_STEAM]
base = "Steam"

# name suffixes

[STR_WAGON_NAME_TRAILER]
base = "Trailer"

# wagon class suffixes
[STR_WAGON_NAME_ACID_TANK_CAR]
base = "Acid Tanker"

[STR_WAGON_NAME_AGGREGATE_BULK_OPEN_CAR]
base = "Stone Wagon"

[STR_WAGON_NAME_AGGREGATE_HOPPER_CAR]
base = "Aggregate Hopper"

[STR_WAGON_NAME_ALIGNMENT_CAR]
base = "Alignment Van"

[STR_WAGON_NAME_AUTOMOBILE_CAR]
base = "Vehicle Transporter"

[STR_WAGON_NAME_BOLSTER_CAR]
base = "Bolster Wagon"

[STR_WAGON_NAME_BOX_CAR]
base = "Box Van"

[STR_WAGON_NAME_BULK_CARGO_BOX_COMBOS]
base = "Mineral Open Wagon"

[STR_WAGON_NAME_BULK_CARGO_HOPPER_COMBOS]
base = "Mineral Hopper"

[STR_WAGON_NAME_BULK_CARGO_MIXED_COMBOS]
base = "Mineral Wagon"

[STR_WAGON_NAME_BULKHEAD_FLAT_CAR_RANDOMISED]
base = "Bulkhead Flat Wagon"

[STR_WAGON_NAME_BULKHEAD_FLAT_CAR]
base = "Bulkhead Flat Wagon"

[STR_WAGON_NAME_CABOOSE_CAR]
base = "Brake Van"

[STR_WAGON_NAME_CANE_BIN_CAR]
base = "Cane Bin"

[STR_WAGON_NAME_CARBON_BLACK_HOPPER_CAR]
base = "Carbon Black Hopper"

[STR_WAGON_NAME_CEMENT_SILO_CAR]
base = "Cement Wagon"

[STR_WAGON_NAME_CHEMICAL_CARGO_TANK_COMBOS]
base = "Chemical Tanker"

[STR_WAGON_NAME_COIL_BUGGY_CAR]
base = "Coil Buggies"

[STR_WAGON_NAME_COIL_CAR]
base = "Coil Carrier"

[STR_WAGON_NAME_COVERED_HOPPER_CAR]
base = "Covered Hopper"

[STR_WAGON_NAME_CRYO_TANK_CAR]
base = "Cryo Tanker"

[STR_WAGON_NAME_CURTAIN_SIDE_BOX_CAR]
base = "Curtain Side Van"

[STR_WAGON_NAME_DOUBLE_DECK_AUTOMOBILE_CAR]
base = "Car Transporter"

[STR_WAGON_NAME_MOTORAIL_AUTOMOBILE_CAR]
base = "Motorail Van"

[STR_WAGON_NAME_EXPRESS_CAR]
base = "Express Van"

[STR_WAGON_NAME_EXPRESS_INTERMODAL_CAR]
base = "Express Container Wagon"

[STR_WAGON_NAME_FARM_CARGO_HOPPER_COMBOS]
base = "Grain Hopper"

[STR_WAGON_NAME_FARM_CARGO_MIXED_COMBOS]
base = "Agricultural Wagon"

[STR_WAGON_NAME_FARM_PRODUCT_BOX_CAR]
base = "Farm Product Van"

[STR_WAGON_NAME_FARM_PRODUCT_HOPPER_CAR]
base = "Farm Product Hopper"

[STR_WAGON_NAME_FLAT_CAR]
base = "General Flat Wagon"

[STR_WAGON_NAME_FLATBED_CARGO_COMBOS]
base = "Flat Wagon"

[STR_WAGON_NAME_FOOD_EXPRESS_BOX_COMBOS]
base = "Express Food Van"

[STR_WAGON_NAME_FOOD_EXPRESS_LIQUID_COMBOS]
base = "Express Beverage Wagon"

[STR_WAGON_NAME_FOOD_EXPRESS_TANK_CAR]
base = "Express Food Tanker"

[STR_WAGON_NAME_FOOD_HOPPER_CAR]
base = "Food Product Hopper"

[STR_WAGON_NAME_FOOD_INGREDIENTS_HOPPER_COMBOS]
base = "Food Ingredients Hopper"

[STR_WAGON_NAME_FOOD_INGREDIENTS_MIXED_COMBOS]
base = "Food Ingredients Wagon"

[STR_WAGON_NAME_HEAVY_DUTY_DUMP_CAR]
base = "Heavy Duty Bulk Wagon"

[STR_WAGON_NAME_HEAVY_DUTY_FLAT_CAR]
base = "Heavy Duty Flat Wagon"

[STR_WAGON_NAME_HIGH_SPEED_MAIL_CAR]
base = "High Speed Mail Van"

[STR_WAGON_NAME_HIGH_SPEED_PASSENGER_CAR]
base = "High Speed Coach"

[STR_WAGON_NAME_HOOD_OPEN_CAR_TYPE_1]
base = "Hood Open Wagon"

[STR_WAGON_NAME_HOPPER_CAR]
base = "Coal Hopper"

[STR_WAGON_NAME_HOPPER_CAR_RANDOMISED]
base = "Coal Hopper"

[STR_WAGON_NAME_HST_MAIL_CAR]
base = "Mail Van"

[STR_WAGON_NAME_HST_PASSENGER_CAR]
base = "Passenger Coach"

[STR_WAGON_NAME_INGOT_CAR]
base = "Ingot Carriers"

[STR_WAGON_NAME_INTERMODAL_CAR]
base = "Container Wagon"

[STR_WAGON_NAME_KAOLIN_HOPPER_CAR]
base = "China Clay Hopper"

[STR_WAGON_NAME_LIME_COVERED_HOPPER_CAR]
base = "Lime Hopper"

[STR_WAGON_NAME_LIVESTOCK_CAR]
base = "Livestock Wagon"

[STR_WAGON_NAME_LIVESTOCK_EXPRESS_CAR]
base = "Livestock Express Van"

[STR_WAGON_NAME_LOG_CAR]
base = "Log Carrier"

[STR_WAGON_NAME_MAIL_CAR]
base = "Mail Van"

[STR_WAGON_NAME_MERCHANDISE_BOX_CAR]
base = "Merchandise Van"

[STR_WAGON_NAME_METAL_PRODUCT_COVERED_COMBOS]
base = "Covered Steel Wagon"

[STR_WAGON_NAME_METAL_PRODUCT_MIXED_COMBOS]
base = "Mixed Steel Wagon"

[STR_WAGON_NAME_MINERAL_BULK_OPEN_CAR]
base = "Coal Wagon"

[STR_WAGON_NAME_MINERAL_BULK_OPEN_CAR_LOW_SIDE]
base = "Sand Wagon"

[STR_WAGON_NAME_MINERAL_COVERED_HOPPER_COMBOS]
base = "Covered Mineral Hopper"

[STR_WAGON_NAME_MGR_HOPPER_CAR]
base = "MGR Hopper"

[STR_WAGON_NAME_MILL_FLAT_CAR]
base = "Mill Flat Wagon"

[STR_WAGON_NAME_MILL_OPEN_CAR]
base = "Mill Open Wagon"

[STR_WAGON_NAME_OPEN_CAR]
base = "General Open Wagon"

[STR_WAGON_NAME_OPEN_CAR_COMBOS]
base = "Open Wagon"

[STR_WAGON_NAME_OPEN_CAR_RANDOMISED]
base = "General Open Wagon"

[STR_WAGON_NAME_PANORAMIC_CAR]
base = "Panoramic Coach"

[STR_WAGON_NAME_PASSENGER_CAR]
base = "Passenger Coach"

[STR_WAGON_NAME_PEAT_CAR]
base = "Peat Wagon"

[STR_WAGON_NAME_PIECE_GOODS_COVERED_COMBOS]
base = "Covered Goods Wagon"

[STR_WAGON_NAME_PIECE_GOODS_MIXED_COMBOS]
base = "Mixed Goods Wagon"

[STR_WAGON_NAME_PIPE_CAR]
base = "Pipe Wagon"

[STR_WAGON_NAME_PRESSURE_TANK_CAR]
base = "Pressure Tanker"

[STR_WAGON_NAME_PRODUCT_TANK_CAR]
base = "Product Tanker"

[STR_WAGON_NAME_REEFER_CAR]
base = "Refrigerated Van"

[STR_WAGON_NAME_RESTAURANT_CAR]
base = "Restaurant Car"

[STR_WAGON_NAME_ROCK_HOPPER_CAR]
base = "Rock Hopper"

[STR_WAGON_NAME_ROLLER_ROOF_HOPPER_CAR]
base = "Roller Roof Hopper"

[STR_WAGON_NAME_SALT_COVERED_HOPPER_CAR]
base = "Salt Hopper"

[STR_WAGON_NAME_SCRAP_METAL_CAR]
base = "Scrap Wagon"

[STR_WAGON_NAME_SIDE_DOOR_HOPPER_CAR]
base = "Side Door Hopper"

[STR_WAGON_NAME_SILO_CAR]
base = "Silo Wagon"

[STR_WAGON_NAME_SKIP_CAR]
base = "Skips"

[STR_WAGON_NAME_SLAG_LADLE_CAR]
base = "Slag Ladle Wagon"

[STR_WAGON_NAME_SLIDING_ROOF_CAR]
base = "Sliding Roof Wagon"

[STR_WAGON_NAME_SLIDING_ROOF_HI_CUBE_CAR]
base = "Cube Wagon"

[STR_WAGON_NAME_SLIDING_WALL_CAR]
base = "Sliding Wall Van"

[STR_WAGON_NAME_SPACER_CAR]
base = "Spacer Wagon"

[STR_WAGON_NAME_SUBURBAN_PASSENGER_CAR]
base = "Suburban Coach"

[STR_WAGON_NAME_SWING_ROOF_HOPPER_CAR]
base = "Swing Roof Hopper"

[STR_WAGON_NAME_TANK_CAR]
base = "General Tanker"

[STR_WAGON_NAME_TARPAULIN_CAR]
base = "Tarpaulin Wagon"

[STR_WAGON_NAME_TIPPLER_BULK_OPEN_CAR]
base = "Tippler Wagon"

[STR_WAGON_NAME_TORPEDO_CAR]
base = "Torpedo Wagon"

[STR_WAGON_NAME_VOLATILES_TANK_CAR]
base = "Volatiles Tanker"

# cargo subtypes - only used for automobile cars (specifically vehicles cargo) as of May 2021
[STR_CARGO_SUBTYPE_VEHI_0]
base = "(Cars)"

[STR_CARGO_SUBTYPE_VEHI_1]
base = "(Trucks)"

[STR_POWER_BY_POWER_SOURCE_TWO_SOURCES]
base = "{BLACK}Power on {STRING}: {GOLD}{POWER} {}{BLACK}Power on {STRING}: {GOLD}{POWER}"

[STR_POWER_SOURCE]
base = "Power Source"

[STR_POWER_SOURCE_OHLE]
base = "Electric"

[STR_POWER_SOURCE_BATTERY_HYBRID]
base = "Battery Hybrid"

[STR_POWER_SOURCE_METRO]
base = "Metro"

[STR_POWER_SOURCE_DIESEL]
base = "Diesel"

[STR_POWER_SOURCE_STEAM]
# reported unused by nml, but needed by docs as of April 2025
base = "Steam"

# assumed to be handling case of lgv_capable (two speeds)
[STR_SPEED_BY_RAILTYPE_LGV_CAPABLE]
base = "{BLACK}Speed (Dedicated High Speed Rail): {GOLD}{VELOCITY} {}{BLACK}Speed (Normal Rail): {GOLD}{VELOCITY}"

# distributed power (dedicated wagons add power)
[STR_WAGONS_ADD_POWER_CAB]
base = "{BLACK}Power (Distributed): {GOLD}{POWER} per {STRING} passenger or mail coach attached"

[STR_WAGONS_ADD_POWER_MIDDLE]
base = "{BLACK}Power (Distributed): {GOLD}{POWER} when attached to {STRING} engine"

# project management
[STR_SPRITES_COMPLETE]
base = "{}Sprites Complete: {GOLD}Yup"

[STR_SPRITES_INCOMPLETE]
base = "{}Sprites Complete: {GOLD}Nope"

## railtypes
# lgv track strings
# this type isn't built, it's unelectrified and exists for compatibility reasons, see electrified lgv instead
[STR_RAILTYPE_LGV_NAME]
base = "Dedicated High Speed Railway"

[STR_RAILTYPE_LGV_TOOLBAR_CAPTION]
base = "[unused]"

[STR_RAILTYPE_LGV_MENU_TEXT]
base = "[unused]"

[STR_RAILTYPE_LGV_BUILD_WINDOW_CAPTION]
base = "New Dedicated High Speed Vehicles"

[STR_RAILTYPE_LGV_AUTOREPLACE_TEXT]
base = "Dedicated High Speed Vehicles"

[STR_RAILTYPE_LGV_NEW_ENGINE_TEXT]
base = "high speed rail vehicle"

# lgv electrified track strings
[STR_RAILTYPE_LGV_ELECTRIFIED_OHLE_NAME]
base = "Dedicated High Speed Railway"

[STR_RAILTYPE_LGV_ELECTRIFIED_OHLE_TOOLBAR_CAPTION]
base = "Dedicated High Speed Railway Construction"

[STR_RAILTYPE_LGV_ELECTRIFIED_OHLE_MENU_TEXT]
base = "Dedicated high speed railway construction"

[STR_RAILTYPE_LGV_ELECTRIFIED_OHLE_BUILD_WINDOW_CAPTION]
base = "New Dedicated High Speed Vehicles"

[STR_RAILTYPE_LGV_ELECTRIFIED_OHLE_AUTOREPLACE_TEXT]
base = "Dedicated High Speed Vehicles"

[STR_RAILTYPE_LGV_ELECTRIFIED_OHLE_NEW_ENGINE_TEXT]
base = "high speed rail vehicle"


# metro track strings
[STR_RAILTYPE_METRO_NAME]
base = "Metro Railway"

[STR_RAILTYPE_METRO_TOOLBAR_CAPTION]
base = "Metro Railway Construction"

[STR_RAILTYPE_METRO_MENU_TEXT]
base = "Metro railway construction"

[STR_RAILTYPE_METRO_BUILD_WINDOW_CAPTION]
base = "New Metro Vehicles"

[STR_RAILTYPE_METRO_AUTOREPLACE_TEXT]
base = "Metro Rail Vehicles"

[STR_RAILTYPE_METRO_NEW_ENGINE_TEXT]
base = "metro rail vehicle"


# narrow gauge track strings
[STR_RAILTYPE_NARROW_GAUGE_NAME]
base = "Narrow Gauge Railway"

[STR_RAILTYPE_NARROW_GAUGE_TOOLBAR_CAPTION]
base = "Narrow Gauge Railway Construction"

[STR_RAILTYPE_NARROW_GAUGE_MENU_TEXT]
base = "Narrow gauge railway construction"

[STR_RAILTYPE_NARROW_GAUGE_BUILD_WINDOW_CAPTION]
base = "New Narrow Gauge Vehicles"

[STR_RAILTYPE_NARROW_GAUGE_AUTOREPLACE_TEXT]
base = "Narrow Gauge Rail Vehicles"

[STR_RAILTYPE_NARROW_GAUGE_NEW_ENGINE_TEXT]
base = "narrow gauge rail vehicle"


# narrow gauge electrified track strings
[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_NAME]
base = "Electrified Narrow Gauge Railway"

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_TOOLBAR_CAPTION]
base = "Electrified Narrow Gauge Railway Construction"

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_MENU_TEXT]
base = "Electrified narrow gauge railway construction"

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_BUILD_WINDOW_CAPTION]
base = "New Electrified Narrow Gauge Vehicles"

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_AUTOREPLACE_TEXT]
base = "Electrified Narrow Gauge Vehicles"

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_NEW_ENGINE_TEXT]
base = "electrified narrow gauge rail vehicle"
