[GLOBAL_PRAGMA]
grflangid = "0x35"
plural = "0"

[STR_GRF_DESCRIPTION]
base = "Lisenssi: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Junien kapasiteetti"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "Mitätön"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "Loistava"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "Kohtuuton"

[STR_BADGE_POWER_SOURCE_DIESEL]
base = "Diesel"

[STR_BADGE_POWER_SOURCE_METRO]
base = "Metro"

[STR_BADGE_POWER_SOURCE_STEAM]
base = "Höyry"

[STR_WAGON_NAME_ALIGNMENT_CAR]
base = "Ryhmitysvaunu"

[STR_WAGON_NAME_CABOOSE_CAR]
base = "Jarruvaunu"

[STR_WAGON_NAME_CRYO_TANK_CAR]
base = "Kryosäiliövaunu"

[STR_WAGON_NAME_CURTAIN_SIDE_BOX_CAR]
base = "Sivupeitevaunu"

[STR_WAGON_NAME_EXPRESS_CAR]
base = "Päivävaunu"

[STR_WAGON_NAME_FLAT_CAR]
base = "Avovaunu"

[STR_WAGON_NAME_INTERMODAL_CAR]
base = "Yhdistettyjen kuljetusten vaunu"

[STR_WAGON_NAME_LIVESTOCK_CAR]
base = "Karjavaunu"

[STR_WAGON_NAME_MAIL_CAR]
base = "Postivaunu"

[STR_WAGON_NAME_OPEN_CAR]
base = "Laidallinen avovaunu"

[STR_WAGON_NAME_PASSENGER_CAR]
base = "Matkustajavaunu"

[STR_WAGON_NAME_TORPEDO_CAR]
base = "Torpedovaunu"

[STR_SPRITES_COMPLETE]
base = "{}Grafiikat piirretty: {GOLD}Kyllä"

[STR_SPRITES_INCOMPLETE]
base = "{}Grafiikat piirretty: {GOLD}Ei"
