[GLOBAL_PRAGMA]
grflangid = "0x03"
plural = "2"
gender = "m m2 f"

[STR_GRF_DESCRIPTION]
base = "Licence: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Capacité des trains"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_DESC]
base = "Ajuste la capacité des véhicules pour d'autres styles de jeu.{}{}Dérisoire{NBSP}: {GOLD}-33%{BLACK}{}Admirable{NBSP}: {GOLD}par défaut{BLACK}{}Démesurée{NBSP}: {GOLD}+33%{BLACK}{}Scandaleuse: {GOLD}+77%{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "Dérisoire"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "Admirable (par défaut)"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "Démesurée"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_3]
base = "Scandaleuse"

[STR_PARAM_SIMPLIFIED_GAMEPLAY_DESC]
base = "Jouer avec une liste de locomotives et de wagons réduite à l'essentiel. Certains véhicules (comme le chasse-neige, les voitures-pilotes et les locomotives très lentes) ne seront pas disponibles."

[STR_PARAM_WAGON_COLOUR_RANDOMISATION]
base = "Randomisation de la couleur des wagons"

[STR_NAME_SUFFIX_DIESEL]
base = "Diesel"

[STR_NAME_SUFFIX_ELECTRODIESEL]
base = "Électro-Diesel"

[STR_NAME_SUFFIX_METRO]
base = "Métro"

[STR_NAME_SUFFIX_STEAM]
base = "Vapeur"

[STR_NAME_SUFFIX_SMALL]
base = "petit"

[STR_NAME_SUFFIX_MEDIUM]
base = "moyen"

[STR_NAME_SUFFIX_LARGE]
base = "grand"

[STR_NAME_SUFFIX_TWIN]
base = "jumeau"

[STR_NAME_SUFFIX_ACID_TANK_CAR]
base = "Citerne d'acide"

[STR_NAME_SUFFIX_ALIGNMENT_CAR]
base = "Fourgon d'alignement"

[STR_NAME_SUFFIX_AUTOMOBILE_CAR]
base = "Wagon porte-véhicule"

[STR_NAME_SUFFIX_BOX_CAR]
base = "Fourgon"

[STR_NAME_SUFFIX_COIL_BUGGY_CAR]
base = "Chariots à bobines"

[STR_NAME_SUFFIX_BOLSTER_CAR]
base = "Wagon plat long"

[STR_NAME_SUFFIX_BULKHEAD_FLAT_CAR]
base = "Wagon plat à cloison"

[STR_NAME_SUFFIX_CABOOSE_CAR]
base = "Fourgon frein"

[STR_NAME_SUFFIX_CEMENT_SILO_CAR]
base = "Wagon cimentier"

[STR_NAME_SUFFIX_CARBON_BLACK_HOPPER_CAR]
base = "Trémie à noir de carbone"

[STR_NAME_SUFFIX_COIL_CAR_COVERED]
base = "Wagon porte-bobines couvert"

[STR_NAME_SUFFIX_COIL_CAR_UNCOVERED]
base = "Wagon porte-bobines"

[STR_NAME_SUFFIX_COVERED_HOPPER_CAR]
base = "Wagon-trémie couvert"

[STR_NAME_SUFFIX_CRYO_TANK_CAR]
base = "Citerne cryogénique"

[STR_NAME_SUFFIX_CURTAIN_SIDE_BOX_CAR]
base = "Wagon à rideau latéral"

[STR_NAME_SUFFIX_DOUBLE_DECK_AUTOMOBILE_CAR]
base = "Wagon porte-automobiles"

[STR_NAME_SUFFIX_DUMP_CAR]
base = "Wagon à minerai"

[STR_NAME_SUFFIX_DUMP_CAR_HIGH_SIDE]
base = "Wagon haut à minerai"

[STR_NAME_SUFFIX_EDIBLES_TANK_CAR]
base = "Citerne alimentaire"

[STR_NAME_SUFFIX_EXPRESS_CAR]
base = "Fourgon express"

[STR_NAME_SUFFIX_EXPRESS_INTERMODAL_CAR]
base = "Wagon porte-container express"

[STR_NAME_SUFFIX_FLAT_CAR]
base = "Wagon plat"

[STR_NAME_SUFFIX_HOPPER_CAR]
base = "Wagon-trémie"

[STR_NAME_SUFFIX_HST_PASSENGER_CAR]
base = "Voiture"

[STR_NAME_SUFFIX_INGOT_CAR]
base = "Wagon porte-lingots"

[STR_NAME_SUFFIX_INTERMODAL_CAR]
base = "Wagon porte-container"

[STR_NAME_SUFFIX_LIVESTOCK_CAR]
base = "Wagon à bétail"

[STR_NAME_SUFFIX_LOG_CAR]
base = "Wagon porte-bûches"

[STR_NAME_SUFFIX_LOW_FLOOR_AUTOMOBILE_CAR]
base = "Wagon porte-automobiles surbaissé"

[STR_NAME_SUFFIX_LOW_FLOOR_INTERMODAL_CAR]
base = "Wagon porte-container surbaissé"

[STR_NAME_SUFFIX_MAIL_CAR]
base = "Fourgon postal"

[STR_NAME_SUFFIX_OPEN_CAR]
base = "Wagon-tombereau"

[STR_NAME_SUFFIX_PASSENGER_CAR]
base = "Voiture"

[STR_NAME_SUFFIX_PEAT_CAR]
base = "Wagon à tourbe"

[STR_NAME_SUFFIX_PLATE_CAR]
base = "Wagon porte-tôles"

[STR_NAME_SUFFIX_PRESSURE_TANK_CAR]
base = "Citerne pressursée"

[STR_NAME_SUFFIX_PRODUCT_TANK_CAR]
base = "Citerne à produits"

[STR_NAME_SUFFIX_RAILBUS_PASSENGER_TRAILER_CAR]
base = "Remorque autorail léger"

[STR_NAME_SUFFIX_RAILCAR_PASSENGER_TRAILER_CAR]
base = "Remorque autorail"

[STR_NAME_SUFFIX_REEFER_CAR_TYPE_1]
base = "Wagon frigorifique"

[STR_NAME_SUFFIX_RESTAURANT_CAR]
base = "Wagon-restaurant"

[STR_NAME_SUFFIX_ROCK_HOPPER_CAR]
base = "Trémie à pierres"

[STR_NAME_SUFFIX_SILO_CAR]
base = "Wagon-silo"

[STR_NAME_SUFFIX_SKIP_CAR]
base = "Tombereaux à bascule"

[STR_NAME_SUFFIX_SLAG_LADLE_CAR]
base = "Wagon-poche"

[STR_NAME_SUFFIX_SLIDING_ROOF_CAR]
base = "Wagon à toit coulissant"

[STR_NAME_SUFFIX_SLIDING_WALL_CAR]
base = "Wagon à parois coulissantes"

[STR_NAME_SUFFIX_SCRAP_METAL_CAR]
base = "Wagon à ferraille"

[STR_NAME_SUFFIX_SUBURBAN_PASSENGER_CAR]
base = "Voiture de banlieue"

[STR_NAME_SUFFIX_TANK_CAR]
base = "Wagon-citerne"

[STR_NAME_SUFFIX_TARPAULIN_CAR]
base = "Wagon bâché"

[STR_NAME_SUFFIX_TORPEDO_CAR]
base = "Wagon-torpille"

[STR_NAME_SUFFIX_VEHICLE_PARTS_BOX_CAR]
base = "Wagon à carrosseries"

[STR_CARGO_SUBTYPE_VEHI_0]
base = "(Voitures)"

[STR_CARGO_SUBTYPE_VEHI_1]
base = "(Camions)"

[STR_ROLE]
base = "{BLACK}Rôle: {GOLD}{STRING}"

[STR_ROLE_DRIVING_CAB]
base = "Voiture-pilote"

[STR_ROLE_FREIGHT]
base = "Fret"

[STR_ROLE_GENERAL_PURPOSE]
base = "Universel"

[STR_ROLE_GENERAL_PURPOSE_EXPRESS]
base = "Universel / Express"

[STR_ROLE_INTERCITY_EXPRESS]
base = "Grande vitesse"

[STR_ROLE_LOLZ]
base = "Blague"

[STR_ROLE_METRO]
base = "Transport de masse urbain"

[STR_ROLE_SUBURBAN]
base = "Transport de banlieue"

[STR_ROLE_VERY_HIGH_SPEED]
base = "Très grande vitesse"

[STR_WAGONS_ADD_POWER_CAB]
base = "Puissance (Distribuée): {GOLD}{POWER} par {STRING} unité attachée"

[STR_WAGONS_ADD_POWER_MIDDLE]
base = "Puissance (Distribuée): {GOLD}{POWER} attaché à une unité {STRING}"

[STR_BUY_MENU_ADDITIONAL_TEXT_HINT_DRIVING_CAB]
base = "{BLACK}Placer à l'avant ou à l'arrière du train, avec au moins une locomotive à l'autre extrémité"

[STR_BUY_MENU_ADDITIONAL_TEXT_HINT_RESTAURANT_CAR]
base = "{}{BLACK}Bonus{NBSP}: {GOLD}Élimine les coûts d'entretien pour toutes les voitures passagers du train"

[STR_SPRITES_COMPLETE]
base = "{}Sprites terminés: {GOLD}Ouaip"

[STR_SPRITES_INCOMPLETE]
base = "{}Sprites terminés: {GOLD}Nan"
