[GLOBAL_PRAGMA]
grflangid = "0x03"
plural = "2"
gender = "m m2 f"

[STR_GRF_DESCRIPTION]
base = "Licence: {SILVER}GPL v2{}{BLACK}"

# parameters (action 14 etc)
[STR_PARAM_ADD_RAILTYPES]
base = "Rails additionnels Iron Horse"
# substrings of the grf name _could_ be used here
ibex = "Rails additionnels Iron Ibex"
moose = "Rails additionnels Iron Moose"

[STR_PARAM_ADD_RAILTYPES_DESC]
base = "Iron Horse inclut des trains nécessitant des types de rail additionnels, par exemple métro et faible écartement. Ces types peuvent aussi être fournis par des GRF alternatifs. Si ces derniers sont utilisés, les rails Iron Horse peuvent être désactivés avec ce paramètre."
# substrings of the grf name _could_ be used here
ibex = "Iron Ibex inclut des trains nécessitant des types de rail additionnels, par exemple métro et faible écartement. Ces types peuvent aussi être fournis par des GRF alternatifs. Si ces derniers sont utilisés, les rails Iron Horse peuvent être désactivés avec ce paramètre."
moose = "Iron Moose inclut des trains nécessitant des types de rail additionnels, par exemple métro et faible écartement. Ces types peuvent aussi être fournis par des GRF alternatifs. Si ces derniers sont utilisés, les rails Iron Horse peuvent être désactivés avec ce paramètre."

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Capacité des trains"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_DESC]
base = "Ajuste la capacité des véhicules pour d'autres styles de jeu.{}{}Nanoscopique: {GOLD}-77%{BLACK}{}Dérisoire{NBSP}: {GOLD}-33%{BLACK}{}Merveilleuse{NBSP}: {GOLD}par défaut{BLACK}{}Démesurée{NBSP}: {GOLD}+33%{BLACK}{}Scandaleuse: {GOLD}+77%{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "Nanoscopique"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "Dérisoire"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "Merveilleuse (par défaut)"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_3]
base = "Démesurée"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_4]
base = "Scandaleuse"

[STR_PARAM_WAGON_COLOUR_RANDOMISATION]
base = "Couleur des wagons nuancée"

[STR_PARAM_WAGON_COLOUR_RANDOMISATION_STRATEGY_DESC]
base = "Nuancer les couleurs des wagons de marchandises ajouter de la variété aux trains (chance aléatoire que chaque wagon soit nuancé)."

[STR_ERROR_INFLATION_INCOMPATIBLE]
base = "Iron Horse n’est pas compatible avec l’inflation d’OpenTTD. Veuillez désactiver l’inflation dans les paramètre d’OpenTTD."
# substrings of the grf name _could_ be used here
ibex = "Iron Ibex n’est pas compatible avec l’inflation d’OpenTTD. Veuillez désactiver l’inflation dans les paramètre d’OpenTTD."
moose = "Iron Moose n’est pas compatible avec l’inflation d’OpenTTD. Veuillez désactiver l’inflation dans les paramètre d’OpenTTD."

[STR_ERROR_TERMITE_DEPRECATED]
base = "Iron Horse inclut désormais les type de rails de Termite. Veuillez retirer Termite des la liste des NewGRF et relancer une partie. Merci."
# substrings of the grf name _could_ be used here
ibex = "Iron Ibex inclut désormais les type de rails de Termite. Veuillez retirer Termite des la liste des NewGRF et relancer une partie. Merci."
moose = "Iron Moose inclut désormais les type de rails de Termite. Veuillez retirer Termite des la liste des NewGRF et relancer une partie. Merci."

# default colours - reuses the constants for the company colour names, so 'COLOUR_' is repeated again in the trailing part of some string names
[STR_BADGE_POWER_SOURCE_BATTERY_HYBRID]
base = "Hybride"

[STR_BADGE_POWER_SOURCE_DIESEL]
base = "Diesel"

[STR_BADGE_POWER_SOURCE_AC]
base = "Électrique alternatif"

[STR_BADGE_POWER_SOURCE_DC]
base = "Électrique continu"

[STR_BADGE_POWER_SOURCE_ELECTRIC_AC_DC]
base = "Électrique universel"

[STR_BADGE_POWER_SOURCE_METRO]
base = "Métro"

[STR_BADGE_POWER_SOURCE_STEAM]
base = "Vapeur"

[STR_WAGON_NAME_TRAILER]
base = "Remorque"

# size suffixes
[STR_WAGON_GROUP_MORE]
# special case
base = "Plus…"

# wagon class suffixes, as of Jan 2019 these are switched from en-us to en-gb; !! consider splitting strings per roster?? A US caboose is still a 'caboose' in en-gb, not a brake van
[STR_WAGON_NAME_ALIGNMENT_CAR]
base = "Fourgon d’alignement"

[STR_WAGON_NAME_AUTOMOBILE_CAR]
base = "Wagon porte-véhicule"

[STR_WAGON_NAME_COIL_BUGGY_CAR]
base = "Chariot à bobines"

[STR_WAGON_NAME_BOLSTER_CAR]
base = "Wagon plat long"

[STR_WAGON_NAME_CABOOSE_CAR]
base = "Fourgon-frein"

[STR_WAGON_NAME_CARBON_BLACK_HOPPER_CAR]
base = "Wagon-trémie à noir de carbone"

[STR_WAGON_NAME_COIL_CAR_COVERED]
base = "Wagon porte-bobines couvert"

[STR_WAGON_NAME_COIL_CAR_UNCOVERED]
base = "Wagon porte-bobines"

[STR_WAGON_NAME_CRYO_TANK_CAR]
base = "Wagon-citerne cryogénique"

[STR_WAGON_NAME_CURTAIN_SIDE_BOX_CAR]
base = "Wagon à rideau latéral"

[STR_WAGON_NAME_DOUBLE_DECK_AUTOMOBILE_CAR]
base = "Wagon porte-automobiles"

[STR_WAGON_NAME_ENCLOSED_AUTOMOBILE_CAR]
base = "Wagon porte-automobiles fermé"

[STR_WAGON_NAME_EXPRESS_CAR]
base = "Fourgon express"

[STR_WAGON_NAME_EXPRESS_INTERMODAL_CAR]
base = "Wagon porte-container express"

[STR_WAGON_NAME_FLAT_CAR]
base = "Wagon plat"

[STR_WAGON_NAME_HEAVY_DUTY_DUMP_CAR]
base= "Wagon de gros renforcé"

[STR_WAGON_NAME_HEAVY_DUTY_FLAT_CAR]
base= "Wagon plat de gros renforcé"

[STR_WAGON_NAME_HIGH_SPEED_MAIL_CAR]
base= "Fourgon postal à grande vitesse"

[STR_WAGON_NAME_HIGH_SPEED_PASSENGER_CAR]
base= "Voiture à grande vitesse"

[STR_WAGON_NAME_HOOD_OPEN_CAR]
base = "Wagon-tombereau bâché"

[STR_WAGON_NAME_HOPPER_CAR]
base = "Wagon-trémie"

[STR_WAGON_NAME_HOPPER_CAR_HIGH_SIDE]
base = "Wagon-trémie haut"

[STR_WAGON_NAME_HST_MAIL_CAR]
base = "Fourgon postal"

[STR_WAGON_NAME_HST_PASSENGER_CAR]
base = "Voiture"

[STR_WAGON_NAME_INGOT_CAR]
base = "Wagon porte-lingots"

[STR_WAGON_NAME_INTERMODAL_CAR]
base = "Wagon porte-container"

[STR_WAGON_NAME_KAOLIN_HOPPER_CAR]
base = "Wagon-trémie à kaolin"

[STR_WAGON_NAME_LIVESTOCK_CAR]
base = "Wagon à bétail"

[STR_WAGON_NAME_LOG_CAR]
base = "Wagon porte-bûches"

[STR_WAGON_NAME_LOW_FLOOR_AUTOMOBILE_CAR]
base = "Wagon porte-automobiles surbaissé"

[STR_WAGON_NAME_LOW_FLOOR_INTERMODAL_CAR]
base = "Wagon porte-container surbaissé"

[STR_WAGON_NAME_MAIL_CAR]
base = "Fourgon postal"

[STR_WAGON_NAME_MERCHANDISE_BOX_CAR]
base = "Fourgon de marchandise"

[STR_WAGON_NAME_MGR_HOPPER_CAR]
base = "Wagon-trémie «{NBSP}carrousel{NBSP}»"

[STR_WAGON_NAME_MGR_TOP_HOOD_HOPPER_CAR]
base = "Wagon-trémie «{NBSP}carrousel{NBSP}» bâché"

[STR_WAGON_NAME_OPEN_CAR]
base = "Wagon-tombereau"

[STR_WAGON_NAME_PANORAMIC_CAR]
base = "Voiture panoramique"

[STR_WAGON_NAME_PASSENGER_CAR]
base = "Voiture"

[STR_WAGON_NAME_PEAT_CAR]
base = "Wagon à tourbe"

[STR_WAGON_NAME_DROP_SIDE_FLAT_CAR]
base = "Wagon porte-tôles"

[STR_WAGON_NAME_PRESSURE_TANK_CAR]
base = "Wagon-citerne pressurisé"

[STR_WAGON_NAME_BULK_CAR_MIXED_RANDOMISED]
base = "Wagon de gros"

[STR_WAGON_NAME_CHEMICAL_TANK_CAR_RANDOMISED]
base = "Wagon-citerne à produits chimiques"

[STR_WAGON_NAME_DEDICATED_COIL_CAR_RANDOMISED]
base = "Wagon porte-bobines"

[STR_WAGON_NAME_FLAT_CAR_RANDOMISED]
base = "Wagon plat"

[STR_WAGON_NAME_METAL_PRODUCT_CAR_MIXED_RANDOMISED]
base = "Wagon porte-bobines"

[STR_WAGON_NAME_HOPPER_CAR_RANDOMISED]
base = "Wagon-trémie"

[STR_WAGON_NAME_OPEN_CAR_RANDOMISED]
base = "Wagon-tombereau"

[STR_WAGON_NAME_PIECE_GOODS_CAR_MIXED_RANDOMISED]
base = "Wagon de pièces détachées"

[STR_WAGON_NAME_RESTAURANT_CAR]
base = "Wagon-restaurant"

[STR_WAGON_NAME_ROCK_HOPPER_CAR]
base = "Wagon-trémie à pierres"

[STR_WAGON_NAME_SKIP_CAR]
base = "Tombereau à bascule"

[STR_WAGON_NAME_SLAG_LADLE_CAR]
base = "Wagon-poche"

[STR_WAGON_NAME_SLIDING_ROOF_CAR]
base = "Wagon à toit coulissant"

[STR_WAGON_NAME_SLIDING_ROOF_HI_CUBE_CAR]
base = "Wagon cube"

[STR_WAGON_NAME_SUBURBAN_PASSENGER_CAR]
base = "Voiture de banlieue"

[STR_WAGON_NAME_SWING_ROOF_HOPPER_CAR]
base = "Wagon-trémie à toit baculant"

[STR_WAGON_NAME_TORPEDO_CAR]
base = "Wagon-torpille"

[STR_CARGO_SUBTYPE_VEHI_0]
base = "(voitures)"

[STR_CARGO_SUBTYPE_VEHI_1]
base = "(camions)"

# role information for buy menu
[STR_BADGE_ROLE]
base = "Rôle"

[STR_BADGE_ROLE_DRIVING_CAB]
base = "Voiture-pilote"

[STR_BADGE_ROLE_GENERAL_PURPOSE]
base = "Universel"

[STR_BADGE_ROLE_GENERAL_PURPOSE_EXPRESS]
base = "Universel / Express"

[STR_BADGE_ROLE_GENERAL_PURPOSE_FREIGHT]
base = "Universel / Fret"

[STR_BADGE_ROLE_GRONK]
base = "Gronk{NBSP}!"

[STR_BADGE_ROLE_INTERCITY_EXPRESS]
base = "Express inter-cités"

[STR_BADGE_ROLE_LOLZ]
base = "Blague"

[STR_BADGE_ROLE_METRO]
base = "Transport de masse urbain"

[STR_BADGE_ROLE_SUBURBAN]
base = "Universel / Haute capacité"

[STR_POWER_BY_POWER_SOURCE_TWO_SOURCES]
base = "{BLACK}Puissance en {STRING}{NBSP}: {GOLD}{POWER} {}{BLACK}Puissance en {STRING}{NBSP}: {GOLD}{POWER}"

[STR_POWER_SOURCE_AC]
base = "courant alternatif"

[STR_POWER_SOURCE_BATTERY_HYBRID]
base = "hybride"

[STR_POWER_SOURCE_DC]
base = "courant continu"

[STR_POWER_SOURCE_METRO]
base = "métro"

[STR_POWER_SOURCE_DIESEL]
base = "diesel"

[STR_POWER_SOURCE_STEAM]
base = "vapeur"

# assumed to be handling case of lgv_capable (two speeds)
[STR_SPEED_BY_RAILTYPE_LGV_CAPABLE]
base = "{BLACK}Vitesse (ligne à grande vitesse dédiée){NBSP}: {GOLD}{VELOCITY} {}{BLACK}Vitesse (rails normaux){NBSP}: {GOLD}{VELOCITY}"

# distributed power (dedicated wagons add power)
[STR_WAGONS_ADD_POWER_CAB]
base = "Puissance (distribuée){NBSP}: {GOLD}{POWER} par {STRING} voiture ou fourgon postal attaché"

[STR_WAGONS_ADD_POWER_MIDDLE]
base = "Puissance (distribuée): {GOLD}{POWER} quand attaché à une locomotive {STRING}"

# project management
[STR_SPRITES_COMPLETE]
base = "{}Sprites terminés: {GOLD}Ouaip"

[STR_SPRITES_INCOMPLETE]
base = "{}Sprites terminés: {GOLD}Nan"

## railtypes
# lgv track strings
# this type isn't built, it's unelectrified and exists for compatibility reasons, see electrified lgv instead
[STR_RAILTYPE_LGV_NAME]
base = "Ligne à grande vitesse dédiée"

[STR_RAILTYPE_LGV_TOOLBAR_CAPTION]
base = "[inutilisée]"

[STR_RAILTYPE_LGV_MENU_TEXT]
base = "[inutilisée]"

[STR_RAILTYPE_LGV_BUILD_WINDOW_CAPTION]
base = "Nouveaux véhicules dédiés à grande vitesse"

[STR_RAILTYPE_LGV_AUTOREPLACE_TEXT]
base = "Véhicules dédiés à grande vitesse"

[STR_RAILTYPE_LGV_NEW_ENGINE_TEXT]
base = "véhicule ferroviaire à grande vitesse"

# lgv electrified track strings
[STR_RAILTYPE_LGV_ELECTRIFIED_NAME]
base = "Ligne à grande vitesse dédiée"

[STR_RAILTYPE_LGV_ELECTRIFIED_TOOLBAR_CAPTION]
base = "Construction de voie ferrée à grande vitesse dédiée"

[STR_RAILTYPE_LGV_ELECTRIFIED_MENU_TEXT]
base = "Construction de voie ferrée à grande vitesse dédiée"

[STR_RAILTYPE_LGV_ELECTRIFIED_BUILD_WINDOW_CAPTION]
base = "Nouveaux véhicules dédiés à grande vitesse"

[STR_RAILTYPE_LGV_ELECTRIFIED_AUTOREPLACE_TEXT]
base = "Véhicules dédiés à grande vitesse"

[STR_RAILTYPE_LGV_ELECTRIFIED_NEW_ENGINE_TEXT]
base = "véhicule ferroviaire à grande vitesse"


# metro track strings
[STR_RAILTYPE_METRO_NAME]
base = "Ligne de métro"

[STR_RAILTYPE_METRO_TOOLBAR_CAPTION]
base = "Construction de voie de métro"

[STR_RAILTYPE_METRO_MENU_TEXT]
base = "Construction de voie de métro"

[STR_RAILTYPE_METRO_BUILD_WINDOW_CAPTION]
base = "Nouveaux métros"

[STR_RAILTYPE_METRO_AUTOREPLACE_TEXT]
base = "Métros"

[STR_RAILTYPE_METRO_NEW_ENGINE_TEXT]
base = "métro"


# narrow gauge track strings
[STR_RAILTYPE_NARROW_GAUGE_NAME]
base = "Voie ferrée à écartement faible"

[STR_RAILTYPE_NARROW_GAUGE_TOOLBAR_CAPTION]
base = "Construction de voie ferrée à écartement faible"

[STR_RAILTYPE_NARROW_GAUGE_MENU_TEXT]
base = "Construction de voie ferrée à écartement faible"

[STR_RAILTYPE_NARROW_GAUGE_BUILD_WINDOW_CAPTION]
base = "Nouveaux véhicules à écartement faible"

[STR_RAILTYPE_NARROW_GAUGE_AUTOREPLACE_TEXT]
base = "Véhicules ferroviaires à écartement faible"

[STR_RAILTYPE_NARROW_GAUGE_NEW_ENGINE_TEXT]
base = "véhicule ferroviaire à écartement faible"


# narrow gauge electrified track strings
[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_NAME]
base = "Voie ferrée à écartement faible électrifiée"

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_TOOLBAR_CAPTION]
base = "Construction de voie ferrée à écartement faible électrifiée"

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_MENU_TEXT]
base = "Construction de voie ferrée à écartement faible électrifiée"

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_BUILD_WINDOW_CAPTION]
base = "Nouveaux véhicules électriques à écartement faible"

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_AUTOREPLACE_TEXT]
base = "Véhicules ferroviaires électriques à écartement faible"

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_NEW_ENGINE_TEXT]
base = "véhicule ferroviaire électrique à écartement faible"


# high clearance track strings
[STR_RAILTYPE_RAIL_HIGH_CLEARANCE_NAME]
base = "Voie ferrée de grande taille"

[STR_RAILTYPE_RAIL_HIGH_CLEARANCE_TOOLBAR_CAPTION]
base = "Construction de voie ferrée de grande taille"

[STR_RAILTYPE_RAIL_HIGH_CLEARANCE_MENU_TEXT]
base = "Construction de voie ferrée de grande taille"

[STR_RAILTYPE_RAIL_HIGH_CLEARANCE_BUILD_WINDOW_CAPTION]
base = "Nouveaux véhicules de grande taille"

[STR_RAILTYPE_RAIL_HIGH_CLEARANCE_AUTOREPLACE_TEXT]
base = "Véhicules de grande taille"

[STR_RAILTYPE_RAIL_HIGH_CLEARANCE_NEW_ENGINE_TEXT]
base = "véhicule ferroviaire de grande taille"


# electrified AC track strings
[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_NAME]
base = "Voie ferrée électrifiée en courant alternatif"

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_TOOLBAR_CAPTION]
base = "Construction de voie ferrée électrifiée en courant alternatif"

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_MENU_TEXT]
base = "Construction de voie ferrée électrifiée en courant alternatif"

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_BUILD_WINDOW_CAPTION]
base = "Nouveaux véhicules électriques en courant alternatif"

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_AUTOREPLACE_TEXT]
base = "Véhicules électriques en courant alternatif"

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_NEW_ENGINE_TEXT]
base = "Véhicule ferroviaire électrique en courant alternatif"

# rail electrified ac dc
[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_DC_NAME]
base = "[inutilisé]"

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_DC_TOOLBAR_CAPTION]
base = "[inutilisé]"

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_DC_MENU_TEXT]
base = "[inutilisé]"

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_DC_BUILD_WINDOW_CAPTION]
base = "Nouveaux véhicules électriques universels"

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_DC_AUTOREPLACE_TEXT]
base = "Véhicules électriques universels"

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_DC_NEW_ENGINE_TEXT]
base = "Véhicule ferroviaire électrique universel"

# rail electrified dc
[STR_RAILTYPE_RAIL_ELECTRIFIED_DC_NAME]
base = "Voie ferrée électrifiée en courant continu"

[STR_RAILTYPE_RAIL_ELECTRIFIED_DC_TOOLBAR_CAPTION]
base = "Construction de voie ferrée électrifiée en courant continu"

[STR_RAILTYPE_RAIL_ELECTRIFIED_DC_MENU_TEXT]
base = "Construction de voie ferrée électrifiée en courant continu"

[STR_RAILTYPE_RAIL_ELECTRIFIED_DC_BUILD_WINDOW_CAPTION]
base = "Nouveaux véhicules électriques en courant continu"

[STR_RAILTYPE_RAIL_ELECTRIFIED_DC_AUTOREPLACE_TEXT]
base = "Véhicules électriques en courant continu"

[STR_RAILTYPE_RAIL_ELECTRIFIED_DC_NEW_ENGINE_TEXT]
base = "Véhicule ferroviaire électrique en courant continu"
