[GLOBAL_PRAGMA]
grflangid = "0x02"
plural = "0"
gender = "m w n p"

[STR_GRF_DESCRIPTION]
base = "Lizenz: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Zugkapazität"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "kümmerlich"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "phänomenal"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "übermäßig"

[STR_BADGE_POWER_SOURCE_DIESEL]
base = "Diesel"

[STR_BADGE_POWER_SOURCE_STEAM]
base = "Dampf"

[STR_WAGON_NAME_CABOOSE_CAR]
base = "Bremserwagen"

[STR_WAGON_NAME_FLAT_CAR]
base = "Flachwagen"

[STR_WAGON_NAME_INTERMODAL_CAR]
base = "Wagen für kombinierten Verkehr"

[STR_WAGON_NAME_LIVESTOCK_CAR]
base = "Viehwagen"

[STR_WAGON_NAME_MAIL_CAR]
base = "Postwagen"

[STR_WAGON_NAME_OPEN_CAR]
base = "offener Wagen"

[STR_WAGON_NAME_PASSENGER_CAR]
base = "Personenwagen"

