[GLOBAL_PRAGMA]
grflangid = "0x5a"
plural = "1"

[STR_GRF_DESCRIPTION]
base = "Lisensi: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Kapapitas Kereta"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_DESC]
base = "Atur Kapapitas Kereta Untuk Kesulitan Permainan.{}{}Puny: {GOLD}33% Lebih Sedikit{BLACK}{}Marvellous: {GOLD}default{BLACK}{}Excessive: {GOLD}33% Lebih Banyak{BLACK}{}Outrageous: {GOLD}77% Lebih Banyak{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "Puny"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "Marvellous (default)"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "Excessive"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_3]
base = "Outrageous"

[STR_PARAM_WAGON_COLOUR_RANDOMISATION]
base = "Warna Gerbong Acak"

[STR_BADGE_POWER_SOURCE_DIESEL]
base = "Diesel"

[STR_BADGE_POWER_SOURCE_METRO]
base = "Metro"

[STR_BADGE_POWER_SOURCE_STEAM]
base = "Uap"

[STR_WAGON_NAME_ALIGNMENT_CAR]
base = "Gerbong Penjajaran"

[STR_WAGON_NAME_COIL_BUGGY_CAR]
base = "Gerbong Koil"

[STR_WAGON_NAME_BOLSTER_CAR]
base = "Gerbong Pendukung"

[STR_WAGON_NAME_CABOOSE_CAR]
base = "Van Rem"

[STR_WAGON_NAME_CARBON_BLACK_HOPPER_CAR]
base = "Gerbong Hopper"

[STR_WAGON_NAME_COIL_CAR_UNCOVERED]
base = "Gerbong Koil"

[STR_WAGON_NAME_CRYO_TANK_CAR]
base = "Gerbong Tanker Cryo"

[STR_WAGON_NAME_CURTAIN_SIDE_BOX_CAR]
base = "Gerbong Tepi Terpal"

[STR_WAGON_NAME_EXPRESS_CAR]
base = "Gerbong Express"

[STR_WAGON_NAME_EXPRESS_INTERMODAL_CAR]
base = "Gerbong Kontainer Express"

[STR_WAGON_NAME_FLAT_CAR]
base = "Gerbong Datar"

[STR_WAGON_NAME_HOPPER_CAR]
base = "Hopper"

[STR_WAGON_NAME_HST_PASSENGER_CAR]
base = "Gerbong Penumpang"

[STR_WAGON_NAME_INGOT_CAR]
base = "Gerbong Penggangkut Logam"

[STR_WAGON_NAME_INTERMODAL_CAR]
base = "Gerbong Kontainer"

[STR_WAGON_NAME_LIVESTOCK_CAR]
base = "Gerbong Ternak"

[STR_WAGON_NAME_LOG_CAR]
base = "Gerbong Kayu"

[STR_WAGON_NAME_MAIL_CAR]
base = "Gerbong Surat/Parcel"

[STR_WAGON_NAME_OPEN_CAR]
base = "Gerbong Terbuka"

[STR_WAGON_NAME_PASSENGER_CAR]
base = "Gerbong Penumpang"

[STR_WAGON_NAME_RESTAURANT_CAR]
base = "Gerbong Restoran"

[STR_WAGON_NAME_ROCK_HOPPER_CAR]
base = "Gerbong Batu"

[STR_WAGON_NAME_SLAG_LADLE_CAR]
base = "Gerbong Terak"

[STR_WAGON_NAME_SLIDING_ROOF_CAR]
base = "Gerbong Atap Geser"

[STR_WAGON_NAME_SUBURBAN_PASSENGER_CAR]
base = "Gerbong Sub urban"

[STR_WAGON_NAME_TORPEDO_CAR]
base = "Gerbong Torpedo"

[STR_BADGE_ROLE]
base = "Role"

[STR_BADGE_ROLE_DRIVING_CAB]
base = "Kabin Kemudi"

[STR_BADGE_ROLE_GENERAL_PURPOSE]
base = "Tujuan Umum"

[STR_BADGE_ROLE_GENERAL_PURPOSE_EXPRESS]
base = "Tujuan Umum Express"

[STR_BADGE_ROLE_INTERCITY_EXPRESS]
base = "Kecepatan Tinggi"

[STR_BADGE_ROLE_LOLZ]
base = "Langsir/tram"

[STR_BADGE_ROLE_METRO]
base = "Urban"

[STR_BADGE_ROLE_SUBURBAN]
base = "Sub Urban"

[STR_WAGONS_ADD_POWER_CAB]
base = "Tenaga (Didistribusikan): {GOLD}{POWER} per {STRING} unit tersambung"

[STR_WAGONS_ADD_POWER_MIDDLE]
base = "Tenaga (Didistribusikan): {GOLD}{POWER} Ketika Di Sambung Dengan {STRING}"

[STR_SPRITES_COMPLETE]
base = "{}Sprite Terselesaikan: {GOLD}Ya"

[STR_SPRITES_INCOMPLETE]
base = "{}Sprites Terselesaikan: {GOLD}Tidak"
