[GLOBAL_PRAGMA]
grflangid = "0x27"
plural = "0"
gender = "m ma f"
case = "fp fs mp ms"

[STR_GRF_DESCRIPTION]
base = "Licenza: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Capacità del treno"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "Squallida"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "Meravigliosa"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "Eccessiva"

[STR_BADGE_POWER_SOURCE_DIESEL]
base = "Diesel"

[STR_BADGE_POWER_SOURCE_ELECTRODIESEL]
base = "Diesel-Elettrica"

[STR_BADGE_POWER_SOURCE_METRO]
base = "Metropolitana"

[STR_BADGE_POWER_SOURCE_STEAM]
base = "(A vapore)"

[STR_BADGE_WAGON_LENGTH_SMALL]
base = "Piccolo"

[STR_BADGE_WAGON_LENGTH_MEDIUM]
base = "Intermedio"

[STR_BADGE_WAGON_LENGTH_LARGE]
base = "Grande"

[STR_WAGON_NAME_ALIGNMENT_CAR]
base = "Carro per allineamento"

[STR_WAGON_NAME_CABOOSE_CAR]
base = "Carro di fine convoglio"

[STR_WAGON_NAME_CURTAIN_SIDE_BOX_CAR]
base = "Carro a tendine laterali"

[STR_WAGON_NAME_EXPRESS_CAR]
base = "Carro per merci leggere"

[STR_WAGON_NAME_FLAT_CAR]
base = "Carro piatto"

[STR_WAGON_NAME_INTERMODAL_CAR]
base = "Carro intermodale"

[STR_WAGON_NAME_LIVESTOCK_CAR]
base = "Carro bestiame"

[STR_WAGON_NAME_MAIL_CAR]
base = "Carro postale"

[STR_WAGON_NAME_OPEN_CAR]
base = "Carro aperto"

[STR_WAGON_NAME_PASSENGER_CAR]
base = "Carrozza passeggeri"

[STR_WAGON_NAME_DROP_SIDE_FLAT_CAR]
base = "Carro piatto"

[STR_BADGE_ROLE]
base = "Ruolo: {GOLD}{STRING}"

[STR_BADGE_ROLE_GENERAL_PURPOSE]
base = "Universale"

[STR_BADGE_ROLE_GENERAL_PURPOSE_EXPRESS]
base = "Merci leggere / Universale"

[STR_BADGE_ROLE_METRO]
base = "Urbano ad alta capacità"

[STR_SPRITES_COMPLETE]
base = "{}Sprite Completi: {GOLD}Sì"

[STR_SPRITES_INCOMPLETE]
base = "{}Sprite Completi: {GOLD}No"
