[GLOBAL_PRAGMA]
grflangid = "0x3a"
plural = "11"
gender = "m f"

[STR_GRF_DESCRIPTION]
base = "라이선스: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "열차 정원"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "매우 작은"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "놀라운"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "과대한"

[STR_NAME_SUFFIX_DIESEL]
base = "디젤"

[STR_NAME_SUFFIX_ELECTRODIESEL]
base = "전기-디젤"

[STR_NAME_SUFFIX_METRO]
base = "도시철도"

[STR_NAME_SUFFIX_STEAM]
base = "증기"

[STR_NAME_SUFFIX_SMALL]
base = "작음"

[STR_NAME_SUFFIX_MEDIUM]
base = "중간"

[STR_NAME_SUFFIX_LARGE]
base = "큼"

[STR_NAME_SUFFIX_ALIGNMENT_CAR]
base = "정렬 차량"

[STR_NAME_SUFFIX_BOX_CAR]
base = "유개차"

[STR_NAME_SUFFIX_CABOOSE_CAR]
base = "제동차"

[STR_NAME_SUFFIX_CRYO_TANK_CAR]
base = "저온 유조차"

[STR_NAME_SUFFIX_CURTAIN_SIDE_BOX_CAR]
base = "커튼 사이드 밴"

[STR_NAME_SUFFIX_DUMP_CAR]
base = "광물화차"

[STR_NAME_SUFFIX_EDIBLES_TANK_CAR]
base = "식품 유조차"

[STR_NAME_SUFFIX_EXPRESS_CAR]
base = "특급 유개화물차"

[STR_NAME_SUFFIX_FLAT_CAR]
base = "평판화차"

[STR_NAME_SUFFIX_INTERMODAL_CAR]
base = "복합 차량"

[STR_NAME_SUFFIX_LIVESTOCK_CAR]
base = "가축 수송 차량"

[STR_NAME_SUFFIX_MAIL_CAR]
base = "우편 수송 차량"

[STR_NAME_SUFFIX_OPEN_CAR]
base = "무개차"

[STR_NAME_SUFFIX_PASSENGER_CAR]
base = "승객 수송 차량"

[STR_NAME_SUFFIX_PLATE_CAR]
base = "평판화차"

[STR_NAME_SUFFIX_REEFER_CAR_TYPE_1]
base = "냉동차"

[STR_NAME_SUFFIX_SILO_CAR]
base = "사일로 화차"

[STR_NAME_SUFFIX_SLIDING_WALL_CAR]
base = "슬라이딩 월 밴"

[STR_NAME_SUFFIX_TANK_CAR]
base = "유조차"

[STR_NAME_SUFFIX_TARPAULIN_CAR]
base = "방수포 화차"

[STR_NAME_SUFFIX_TORPEDO_CAR]
base = "어뢰 화차"

[STR_SPRITES_COMPLETE]
base = "{}스트라이트 완성: {GOLD}됨"

[STR_SPRITES_INCOMPLETE]
base = "{}스프라이트 완성: {GOLD}안 됨"
