[GLOBAL_PRAGMA]
grflangid = "0x3a"
plural = "11"
gender = "m f"

[STR_GRF_DESCRIPTION]
base = "라이선스: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "열차 정원"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "매우 작은"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "놀라운"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "과대한"

[STR_BADGE_POWER_SOURCE_DIESEL]
base = "디젤"

[STR_BADGE_POWER_SOURCE_METRO]
base = "도시철도"

[STR_BADGE_POWER_SOURCE_STEAM]
base = "증기"

[STR_WAGON_NAME_ALIGNMENT_CAR]
base = "정렬 차량"

[STR_WAGON_NAME_CABOOSE_CAR]
base = "제동차"

[STR_WAGON_NAME_CRYO_TANK_CAR]
base = "저온 유조차"

[STR_WAGON_NAME_CURTAIN_SIDE_BOX_CAR]
base = "커튼 사이드 밴"

[STR_WAGON_NAME_EXPRESS_CAR]
base = "특급 유개화물차"

[STR_WAGON_NAME_FLAT_CAR]
base = "평판화차"

[STR_WAGON_NAME_INTERMODAL_CAR]
base = "복합 차량"

[STR_WAGON_NAME_LIVESTOCK_CAR]
base = "가축 수송 차량"

[STR_WAGON_NAME_MAIL_CAR]
base = "우편 수송 차량"

[STR_WAGON_NAME_OPEN_CAR]
base = "무개차"

[STR_WAGON_NAME_PASSENGER_CAR]
base = "승객 수송 차량"

[STR_WAGON_NAME_DROP_SIDE_FLAT_CAR]
base = "평판화차"

[STR_WAGON_NAME_TORPEDO_CAR]
base = "어뢰 화차"

[STR_SPRITES_COMPLETE]
base = "{}스트라이트 완성: {GOLD}됨"

[STR_SPRITES_INCOMPLETE]
base = "{}스프라이트 완성: {GOLD}안 됨"
