[GLOBAL_PRAGMA]
grflangid = "0x66"
plural = "0"
gender = "m f n mp fp np"
case = "abl acc dat gen"

[STR_GRF_DESCRIPTION]
base = "Licentia: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Capacitates traminum"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "Exiguae"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "Optimae"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "Nimiae"

[STR_NAME_SUFFIX_DIESEL]
base = "(Diseliana)"

[STR_NAME_SUFFIX_ELECTRODIESEL]
base = "(Electrica Diselianaque)"

[STR_NAME_SUFFIX_STEAM]
base = "(Vaporaria)"

[STR_NAME_SUFFIX_BOX_CAR]
base = "Currus Clausus"

[STR_NAME_SUFFIX_CABOOSE_CAR]
base = "Currus Postremus"

[STR_NAME_SUFFIX_FOOD_TANK_CAR]
base = "Currus Cisterninus Edulium"

[STR_NAME_SUFFIX_FLAT_CAR]
base = "Currus Planus"

[STR_NAME_SUFFIX_LIVESTOCK_CAR]
base = "Currus Pecuarius"

[STR_NAME_SUFFIX_MAIL_CAR]
base = "Currus Cursualis"

[STR_NAME_SUFFIX_OPEN_CAR]
base = "Currus Apertus"

[STR_NAME_SUFFIX_PASSENGER_CAR]
base = "Currus Vectorius"

[STR_NAME_SUFFIX_REEFER_CAR_TYPE_1]
base = "Currus Frigidarius"

[STR_NAME_SUFFIX_TANK_CAR]
base = "Currus Cisterninus"
