[GLOBAL_PRAGMA]
grflangid = "0x66"
plural = "0"
gender = "m f n mp fp np"
case = "abl acc dat gen"

[STR_GRF_DESCRIPTION]
base = "Licentia: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Capacitates traminum"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "Exiguae"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "Optimae"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "Nimiae"

[STR_BADGE_POWER_SOURCE_DIESEL]
base = "(Diseliana)"

[STR_BADGE_POWER_SOURCE_ELECTRODIESEL]
base = "(Electrica Diselianaque)"

[STR_BADGE_POWER_SOURCE_STEAM]
base = "(Vaporaria)"

[STR_WAGON_NAME_CABOOSE_CAR]
base = "Currus Postremus"

[STR_WAGON_NAME_FLAT_CAR]
base = "Currus Planus"

[STR_WAGON_NAME_LIVESTOCK_CAR]
base = "Currus Pecuarius"

[STR_WAGON_NAME_MAIL_CAR]
base = "Currus Cursualis"

[STR_WAGON_NAME_OPEN_CAR]
base = "Currus Apertus"

[STR_WAGON_NAME_PASSENGER_CAR]
base = "Currus Vectorius"

