[GLOBAL_PRAGMA]
grflangid = "0x23"
plural = "0"

[STR_GRF_DESCRIPTION]
base = "Lizens: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Zuchkapazitéit"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "Mickreg"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "Herrlech"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "Exzessiv"

[STR_NAME_SUFFIX_DIESEL]
base = "(Diesel)"

[STR_NAME_SUFFIX_ELECTRODIESEL]
base = "(Elektro-Diesel)"

[STR_NAME_SUFFIX_STEAM]
base = "(Damp)"

[STR_NAME_SUFFIX_BOX_CAR_TYPE_1]
base = "Këschtewaggon"

[STR_NAME_SUFFIX_CABOOSE_CAR]
base = "Begleedwaggon"

[STR_NAME_SUFFIX_FOOD_TANK_CAR]
base = "Liewensmëtteltankwaggon"

[STR_NAME_SUFFIX_FLAT_CAR]
base = "Flaachbettwaggon"

[STR_NAME_SUFFIX_LIVESTOCK_CAR]
base = "Véiwaggon"

[STR_NAME_SUFFIX_MAIL_CAR]
base = "Postwaggon"

[STR_NAME_SUFFIX_OPEN_CAR]
base = "Openen Waggon"

[STR_NAME_SUFFIX_PASSENGER_CAR]
base = "Passagéierwaggon"

[STR_NAME_SUFFIX_REEFER_CAR_TYPE_1]
base = "Killwaggon"

[STR_NAME_SUFFIX_TANK_CAR]
base = "Tankwaggon"
