[GLOBAL_PRAGMA]
grflangid = "0x23"
plural = "0"

[STR_GRF_DESCRIPTION]
base = "Lizens: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Zuchkapazitéit"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "Mickreg"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "Herrlech"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "Exzessiv"

[STR_BADGE_POWER_SOURCE_DIESEL]
base = "(Diesel)"

[STR_BADGE_POWER_SOURCE_ELECTRODIESEL]
base = "(Elektro-Diesel)"

[STR_BADGE_POWER_SOURCE_STEAM]
base = "(Damp)"

[STR_WAGON_NAME_CABOOSE_CAR]
base = "Begleedwaggon"

[STR_WAGON_NAME_FLAT_CAR]
base = "Flaachbettwaggon"

[STR_WAGON_NAME_LIVESTOCK_CAR]
base = "Véiwaggon"

[STR_WAGON_NAME_MAIL_CAR]
base = "Postwaggon"

[STR_WAGON_NAME_OPEN_CAR]
base = "Openen Waggon"

[STR_WAGON_NAME_PASSENGER_CAR]
base = "Passagéierwaggon"

