[GLOBAL_PRAGMA]
grflangid = "0x55"
plural = "0"
gender = "m f"

[STR_GRF_DESCRIPTION]
base = "Licencia: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Capacidad del tren"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "Mínima"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "Maravillosa"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "Excesiva"

[STR_NAME_SUFFIX_DIESEL]
base = "(diésel)"

[STR_NAME_SUFFIX_ELECTRODIESEL]
base = "(diésel eléctrica)"

[STR_NAME_SUFFIX_STEAM]
base = "(vapor)"

[STR_NAME_SUFFIX_BOX_CAR_TYPE_1]
base = "Furgón"

[STR_NAME_SUFFIX_CABOOSE_CAR]
base = "Cabús"

[STR_NAME_SUFFIX_FLAT_CAR]
base = "Plataforma"

[STR_NAME_SUFFIX_LIVESTOCK_CAR]
base = "Vagón de ganado"

[STR_NAME_SUFFIX_MAIL_CAR]
base = "Vagón postal"

[STR_NAME_SUFFIX_OPEN_CAR]
base = "Vagón abierto"

[STR_NAME_SUFFIX_PASSENGER_CAR]
base = "Coche de pasajeros"

[STR_NAME_SUFFIX_REEFER_CAR_TYPE_1]
base = "Vagón refrigerado"

[STR_NAME_SUFFIX_TANK_CAR]
base = "Carro tanque"
