[GLOBAL_PRAGMA]
grflangid = "0x04"
plural = "0"
gender = "m f"

[STR_GRF_DESCRIPTION]
base = "Licencia: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Capacidad del tren"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_DESC]
base = "Ajusta la capacidad del tren para estilos de juego alternativos.{}{}Puny: {GOLD}Reducción del 33%{BLACK}{}Marvellous: {GOLD}por defecto{BLACK}{}Excesivo: {GOLD}Incremento del 33%{BLACK}{}Desmesurado: {GOLD}Incremento del 77%{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "Insignificante"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "Maravillosa"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "Excesiva"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_3]
base = "Desmesurado"

[STR_PARAM_WAGON_COLOUR_RANDOMISATION]
base = "Selección de color de vagón aleatorio"

[STR_BADGE_POWER_SOURCE_DIESEL]
base = "Diésel"

[STR_BADGE_POWER_SOURCE_METRO]
base = "Metro"

[STR_BADGE_POWER_SOURCE_STEAM]
base = "Vapor"

[STR_WAGON_NAME_ALIGNMENT_CAR]
base = "Vagón de alineamiento"

[STR_WAGON_NAME_COIL_BUGGY_CAR]
base = "Vagón de bobinado"

[STR_WAGON_NAME_BOLSTER_CAR]
base = "Vagón de carga plana"

[STR_WAGON_NAME_CABOOSE_CAR]
base = "Vagón de cola"

[STR_WAGON_NAME_CARBON_BLACK_HOPPER_CAR]
base = "Vagón carbonero"

[STR_WAGON_NAME_COIL_CAR_COVERED]
base = "Vagón de bobinado cubierto"

[STR_WAGON_NAME_COIL_CAR_UNCOVERED]
base = "Vagón de bobinado abierto"

[STR_WAGON_NAME_CRYO_TANK_CAR]
base = "Vagón tanque de hidrógeno líquido"

[STR_WAGON_NAME_CURTAIN_SIDE_BOX_CAR]
base = "Vagón de cortina lateral"

[STR_WAGON_NAME_EXPRESS_CAR]
base = "Vagón express"

[STR_WAGON_NAME_EXPRESS_INTERMODAL_CAR]
base = "Vagón contenedor express"

[STR_WAGON_NAME_FLAT_CAR]
base = "Vagón plano"

[STR_WAGON_NAME_HOPPER_CAR]
base = "Vagón tolva"

[STR_WAGON_NAME_HST_PASSENGER_CAR]
base = "Vagón de pasaje de alta velocidad"

[STR_WAGON_NAME_INGOT_CAR]
base = "Vagón metalero"

[STR_WAGON_NAME_INTERMODAL_CAR]
base = "Vagón contenedor"

[STR_WAGON_NAME_LIVESTOCK_CAR]
base = "Vagón de ganado"

[STR_WAGON_NAME_LOG_CAR]
base = "Vagón de madera"

[STR_WAGON_NAME_LOW_FLOOR_INTERMODAL_CAR]
base = "Vagón contenedor bajo"

[STR_WAGON_NAME_MAIL_CAR]
base = "Vagón de correo"

[STR_WAGON_NAME_OPEN_CAR]
base = "Vagón abierto"

[STR_WAGON_NAME_PASSENGER_CAR]
base = "Vagón de pasaje"

[STR_WAGON_NAME_DROP_SIDE_FLAT_CAR]
base = "Vagón platero"

[STR_WAGON_NAME_RESTAURANT_CAR]
base = "Vagón restaurante"

[STR_WAGON_NAME_ROCK_HOPPER_CAR]
base = "Vagón de minerales"

[STR_WAGON_NAME_SLAG_LADLE_CAR]
base = "Vagón de escoria metalúrgica"

[STR_WAGON_NAME_SLIDING_ROOF_CAR]
base = "Vagón de techo deslizante"

[STR_WAGON_NAME_TORPEDO_CAR]
base = "Vagón torpedo"

[STR_BADGE_ROLE]
base = "Rol"

[STR_BADGE_ROLE_DRIVING_CAB]
base = "Cabina de Conducción"

[STR_BADGE_ROLE_GENERAL_PURPOSE]
base = "Propósito General"

[STR_BADGE_ROLE_GENERAL_PURPOSE_EXPRESS]
base = "Propósito General / Express"

[STR_BADGE_ROLE_INTERCITY_EXPRESS]
base = "Alta Velocidad"

[STR_BADGE_ROLE_LOLZ]
base = "Gronk!"

[STR_BADGE_ROLE_METRO]
base = "Urbano de Alta Capacidad"

[STR_WAGONS_ADD_POWER_CAB]
base = "Potencia (Distribuída): {GOLD}{POWER} por cada {STRING} unidad adjuntada"

[STR_WAGONS_ADD_POWER_MIDDLE]
base = "Potencia (Distribuída): {GOLD}{POWER} al adjuntar {STRING} unidad"

[STR_SPRITES_COMPLETE]
base = "{}Sprites Completados: {GOLD}Sip"

[STR_SPRITES_INCOMPLETE]
base = "{}Sprites Completados: {GOLD}Nop"
