[STR_CARGO_SUBTYPE_VEHI_0]
# temp, expected to be used by vehicle carriers
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_CARGO_SUBTYPE_VEHI_1]
# temp, expected to be used by vehicle carriers
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_SPRITES_COMPLETE]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_SPRITES_INCOMPLETE]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_WAGON_NAME_ALIGNMENT_CAR]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_POWER_SOURCE_BATTERY_HYBRID]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_POWER_SOURCE_DC]
suppressed_rosters = ["pony", "moose"]

[STR_POWER_SOURCE_METRO]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_BADGE_POWER_SOURCE_ELECTRIC_DC]
suppressed_rosters = ["pony", "moose"]

[STR_BADGE_POWER_SOURCE_ELECTRIC_AC_DC]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_NAME]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_TOOLBAR_CAPTION]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_MENU_TEXT]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_BUILD_WINDOW_CAPTION]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_AUTOREPLACE_TEXT]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_NEW_ENGINE_TEXT]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_DC_NAME]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_DC_TOOLBAR_CAPTION]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_DC_MENU_TEXT]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_DC_BUILD_WINDOW_CAPTION]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_DC_AUTOREPLACE_TEXT]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_DC_NEW_ENGINE_TEXT]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_DC_NAME]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_DC_TOOLBAR_CAPTION]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_DC_MENU_TEXT]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_DC_BUILD_WINDOW_CAPTION]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_DC_AUTOREPLACE_TEXT]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_DC_NEW_ENGINE_TEXT]
suppressed_rosters = ["pony", "moose"]

[STR_WAGON_NAME_BULKHEAD_FLAT_CAR]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_WAGON_NAME_BULKHEAD_FLAT_CAR_RANDOMISED]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_WAGON_NAME_TRAILER]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_AGGREGATE_BULK_OPEN_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_AUTOMOBILE_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_BOLSTER_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_BULK_CAR_BOX_RANDOMISED]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_BULK_CAR_HOPPER_RANDOMISED]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_BULK_CAR_MIXED_RANDOMISED]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_CABOOSE_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_CANE_BIN_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_CHEMICAL_TANK_CAR_RANDOMISED]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_COIL_BUGGY_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_COVERED_BULK_CAR_RANDOMISED]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_CURTAIN_SIDE_BOX_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_DEDICATED_COIL_CAR_RANDOMISED]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_DOUBLE_DECK_AUTOMOBILE_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_ENCLOSED_AUTOMOBILE_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_EXPRESS_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_EXPRESS_FOOD_CAR_RANDOMISED]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_HIGH_SPEED_MAIL_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_HIGH_SPEED_PASSENGER_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_HOOD_OPEN_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_HOPPER_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_HOPPER_CAR_HIGH_SIDE]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_HOPPER_CAR_RANDOMISED]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_HST_MAIL_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_HST_PASSENGER_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_LIVESTOCK_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_LOW_FLOOR_AUTOMOBILE_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_MAIL_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_METAL_PRODUCT_CAR_COVERED_RANDOMISED]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_METAL_PRODUCT_CAR_MIXED_RANDOMISED]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_METAL_PRODUCT_CAR_UNCOVERED_RANDOMISED]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_MINERAL_BULK_OPEN_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_MINERAL_BULK_OPEN_CAR_HIGH_SIDE]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_MINERAL_BULK_OPEN_CAR_LOW_SIDE]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_MGR_HOPPER_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_MGR_TOP_HOOD_HOPPER_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_MILL_OPEN_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_OPEN_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_OPEN_CAR_RANDOMISED]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_PANORAMIC_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_PASSENGER_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_PEAT_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_PIECE_GOODS_CAR_COVERED_RANDOMISED]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_PIECE_GOODS_CAR_MANUFACTURING_PARTS_RANDOMISED]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_PIECE_GOODS_CAR_MIXED_RANDOMISED]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_RESTAURANT_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_ROCK_HOPPER_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_SALT_COVERED_HOPPER_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_SKIP_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_SLIDING_ROOF_HI_CUBE_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_SUBURBAN_PASSENGER_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_SWING_ROOF_HOPPER_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_BADGE_POWER_SOURCE_ELECTRIC_AC]
suppressed_rosters = ["moose"]

[STR_BADGE_POWER_SOURCE_ELECTRODIESEL]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_ACID_TANK_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_AGGREGATE_HOPPER_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_BOX_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_CARBON_BLACK_HOPPER_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_CEMENT_SILO_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_COIL_CAR_COVERED]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_COIL_CAR_UNCOVERED]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_COVERED_HOPPER_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_CRYO_TANK_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_DROP_END_FLAT_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_DROP_SIDE_FLAT_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_EXPRESS_INTERMODAL_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_FARM_PRODUCT_BOX_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_FARM_PRODUCT_HOPPER_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_FLAT_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_FLAT_CAR_RANDOMISED]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_FOOD_HOPPER_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_FOOD_EXPRESS_TANK_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_HEAVY_DUTY_DUMP_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_HEAVY_DUTY_FLAT_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_INGOT_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_INTERMODAL_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_KAOLIN_HOPPER_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_LIME_COVERED_HOPPER_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_LOG_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_LOW_FLOOR_INTERMODAL_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_MERCHANDISE_BOX_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_MILL_FLAT_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_PIPE_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_PRESSURE_TANK_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_PRODUCT_TANK_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_REEFER_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_ROLLER_ROOF_HOPPER_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_SCRAP_METAL_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_SIDE_DOOR_HOPPER_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_SILO_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_SLAG_LADLE_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_SLIDING_ROOF_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_SLIDING_WALL_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_TANK_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_TARPAULIN_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_TIPPLER_BULK_OPEN_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_TIPPLER_ROTARY_BULK_OPEN_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_WAGON_NAME_TORPEDO_CAR]
suppressed_rosters = ["moose"]

[STR_WAGON_NAME_VOLATILES_TANK_CAR]
suppressed_rosters = ["moose", "ibex"]

[STR_POWER_BY_POWER_SOURCE_TWO_SOURCES]
suppressed_rosters = ["moose"]

[STR_POWER_SOURCE_AC]
suppressed_rosters = ["moose"]

[STR_POWER_SOURCE_DIESEL]
suppressed_rosters = ["moose"]

[STR_SPEED_BY_RAILTYPE_LGV_CAPABLE]
suppressed_rosters = ["moose"]

[STR_WAGONS_ADD_POWER_CAB]
suppressed_rosters = ["moose"]

[STR_WAGONS_ADD_POWER_MIDDLE]
suppressed_rosters = ["moose"]

