[GLOBAL_PRAGMA]
grflangid = "0x2e"
plural = "0"

[STR_GRF_DESCRIPTION]
base = "Licens: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Tågkapacitet"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "Väldigt liten"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "Enastående"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "Överdriven"

[STR_BADGE_POWER_SOURCE_DIESEL]
base = "Diesel"

[STR_BADGE_POWER_SOURCE_METRO]
base = "Tunnelbana"

[STR_BADGE_POWER_SOURCE_STEAM]
base = "Ånga"

[STR_WAGON_NAME_CABOOSE_CAR]
base = "Bromsvagn"

[STR_WAGON_NAME_FLAT_CAR]
base = "Flakvagn"

[STR_WAGON_NAME_INTERMODAL_CAR]
base = "Kombinationsflakvagn"

[STR_WAGON_NAME_LIVESTOCK_CAR]
base = "Boskapsvagn"

[STR_WAGON_NAME_MAIL_CAR]
base = "Postvagn"

[STR_WAGON_NAME_OPEN_CAR]
base = "Öppen Vagn"

[STR_WAGON_NAME_PASSENGER_CAR]
base = "Passagerarvagn"

